### ISSUE TITLE
Problem with force time out

### ISSUE THREAD

**Issue by nhimcoi30889** [nodogsplash/nodogsplash#119]
Hi everybody,
I meet a problem as : 
- i use nodogsplash with no-authent ( press dog icon to internet )
- i configured as guideline of @lynxis @mwarning @bluewarenet at https://github.com/nodogsplash/nodogsplash/issues/46
  All working perfect but have a problem. When i set Forcetimeout at /etc/nodogsplash/nodogsplash.conf .( example 15 mins ). After 15 mins, client force disconnect internet ( clear client list - ndsctl status ) . But devices dont push pop-up as first time connect AP. End-user need open browser and re-authent to continue use internet. So, many times, end-users dont know expired session ( dont open browser reauthent ), so they think that dont have internet connection

You can give me solution for push pop-up auto after expired force time out ?

**Comment by nhimcoi30889** [comment]
@lynxis @mwarning @bluewarenet , can you help me ?

**Comment by bluewavenet** [comment]
This is outside any possible control of Nodogsplash and is entirely up to the mobile device's Captive Portal Detection function. This varies from operating system to operating system and version to version.

Force timeout is working, but the OS just assumes the Internet is down as it just comes to an abrupt halt.
At this point if the user disconnects from wifi, "forgets" the ssid, then reconnects, the portal detection will do its job. But this does not solve your problem.

Instead you should set the inactivity timer instead. If the os sees no traffic for a period, on an app trying to send data,  the os will first try first portal detection, AND if Nodogsplash has disconnected you will get the popup.

I suggest forced timeout  > or = 600, and inactivity timeout > or = 30 as a starting point.

Do also make sure that your router has ipv6 dhcp disabled otherwise you will have long delays induced in the portal detection.

**Comment by nhimcoi30889** [comment]
Hi @bluewavenet ,
Thank for answer, so at the moment , dont have a solution thoroughly with nodogsplash.
Can you tell me more detail about `set the inactivity timer instead. If the os sees no traffic for a period, on an app trying to send data, the os will first try first portal detection, AND if Nodogsplash has disconnected you will get the popup.`
Thanks

**Comment by bluewavenet** [comment]
For example in nodogsplash.conf make sure you have:
`# ClientIdleTimeout
# Parameter: ClientIdleTimeout
# Default: 10
#
# Set ClientIdleTimeout to the desired of number of minutes
# of inactivity before a user is automatically 'deauthenticated'.
#
ClientIdleTimeout 30

# Parameter: ClientForceTimeout
# Default: 360
#
# Set ClientForceTimeout to the desired number of minutes before
# a user is automatically 'deauthenticated', whether active or not
#
ClientForceTimeout 600`

**Comment by nhimcoi30889** [comment]
Oh, my file setup as bellow. But i mean 

> If the os sees no traffic for a period, on an app trying to send data, the os will first try first portal detection, AND if Nodogsplash has disconnected you will get the popup.

**Comment by bluewavenet** [comment]
Typically the operating system of a mobile device, on connection to WiFi, will try to connect to a specific service. If it fails but has a good ip connection it will assume it is connected to a captive portal, or Hotspot controller such as Nodogsplash and start the device's default browser for authentication.
If you force timeout, the operating system assumes the Internet has gone down and not restart it's captive portal detection.
If you idle timeout, this means if the mobile device does not send and traffic for the set interval, Nodogsplash will disconnect. Also the device will drop its WiFi connection (to save battery). When the device is asked to send data again, the WiFi will wake up, re-connect and the os will restart the captive portal detection.
If you search "Captive Portal Detection" on Google you will find a lot to read but you will find it is not at all a standard.
