### ISSUE TITLE
Check nodogsplash working from remote

### ISSUE THREAD

**Issue by nhimcoi30889** [nodogsplash/nodogsplash#121]
Hi everybody,
I think about a problem as : 
- i have a router running openwrt + nodogsplash. Its working perfect ( pop-up authent, redirect ... )
- i can access router from remote machine ( vpn ) for ssh
- about 2 or 3 , router can pending status ( client connect to router but dont show pop-up, so client cant press icon access internet )
- ssh to router and ping internet normally
  ==> i need reboot router or trouble some problem , after client can access internet
  I want to ask you : can simulator a device client for test this case ( remote simulator ) ???
  I cant go to router for check ( use my smphone test ) everytime

**Comment by nhimcoi30889** [comment]
@lynxis @mwarning @bluewarenet can you give some solution ?

**Comment by bluewavenet** [comment]
You can use ndsctl status to check if it is working and /etc/init.d/nodogsplash stop
And 
/etc/init.d/nodogsplash start 
to restart it. Also the reboot command to restart the router.
Usually if clients fail to be redirected it means they are not resolving dns.  Can also happen if the router is VERY short of memory. Check the system logs and kernel logs for errors.
What router/openwrt/nodogsplash are you using?

**Comment by nhimcoi30889** [comment]
Tks @bluewavenet ,
Im using openwrt CC 15.5.01 , nodogsplash 0.9.9.5, router tplink c20i ( ram 64mb, flash 8mb ).
I think that 64mb ram is not short

**Comment by nhimcoi30889** [comment]
Can i increase speed resolve dns ?

**Comment by nhimcoi30889** [comment]
Hi @bluewavenet ,
I have another case as : 
I use a web server for redirect URL
Sometime, my web server response very slow or down.
This time, client's request will take time very long for resolve dns or receive response web server before show page not found
I want it redirect to primary URL about 5s, if dont receive response from my web server, it'll redirect to another URL ( second url )
I can do it ?

**Comment by bluewavenet** [comment]
This is not a problem with Nodogsplash and I do not know of anything to do this. It would be better to fix your web server. Why not run your web server on your router? uhttpd is there and running already on Openwrt and it supports PHP.
Likewise, slow DNS is nothing to do with Nodogsplash and is most likely due to an issue with the Internet feed you are using.

**Comment by nhimcoi30889** [comment]
I think that can't use openwrt as web server because the flash store slow (8mb)
I read your topic : https://github.com/nodogsplash/nodogsplash/issues/113
Time response splash page average about 7s
You think its slow or normal ?
Time response on your system ?

**Comment by misterlexa** [comment]
You can use simple cron.
Create sh script like this:

if pgrep "nodogsplash" > /dev/null
then
    command wget "http://www.mysite.com/nodogsplash?works=1
else
    command wget "http://www.mysite.com/nodogsplash?works=0
    command /etc/init.d/nodogsplash start
fi

then: 
crontab -e
and 
* * * * * /path/to/your/script.sh;

**Comment by bluewavenet** [comment]
@nhimcoi30889 
On Ubiquiti Bullet M2, Nanostation M2, AirGateway LR, and PCEngines Alix 2d2 : Response time <2 seconds on all of these. Alix 2d2 supporting over 350 Nodogsplash connections per day and peak of ~60 simultaneous users and still <2 sec to splash page.

**Comment by nhimcoi30889** [comment]
Hi @bluewavenet ,
Can you tell me which does element that decide response time for landing page ?

**Comment by bluewavenet** [comment]
The biggest element controlling response time to splash page is the response time of your Internet feed. The client device has to resolve dns then make a request on port 80 before being redirected. 99.9% of devices on a hotspot will be mobile "smartphone" or "tablet" rather than "laptop" and these devices all have a similar means of detecting a hotspot which depends upon dns.  This is called portal detection and varies depending on operating system but has a short timeout for detection at which point will disconnect its wifi and then retry in the background. If your Internet feed is very slow the portal detection can get into an infinite loop. This is nothing to do with Nodogsplash and everything to do with your router's connection.

**Comment by nhimcoi30889** [comment]
I think have a problem. landing page ( splash page ) on AP locally, so internet feed dont decide ?

**Comment by bluewavenet** [comment]
The response time from the Internet for the dns resolution of the requested web page on port 80 is the dominant factor in the time taken for the splash page held on the router to be served up. So yes, the Internet feed does "decide".

**Comment by nhimcoi30889** [comment]
I can use AP for DNS server ? When client request dns resolution, it'll broadcast to AP locally first ( or i can define dns on hosts file ? )

**Comment by bluewavenet** [comment]
Nodogsplash has to run on a router and by default OpenWrt will provide dhcp and dns to clients. Setting up any other way just makes it unnecessarily complicated. 
This is all designed to provide Internet access on acceptance of terms and conditions (usually provided by your customised splash page). It sounds like you need to fix your Internet feed first.
