### ISSUE TITLE
Trouble using remote authentication and EnablePreauth

### ISSUE THREAD

**Issue by phenobarbital** [nodogsplash/nodogsplash#138]
I'm using EnablePreauth for remote mac address authentication, it works as expected with this configuration:
BinVoucher /usr/local/bin/preauth
EnablePreAuth 1
ForceVoucher 0

but script is called over and over again until authentication:
Sat Sep 17 08:00:49 2016 user.notice preauth: sendind pre-auth
Sat Sep 17 08:00:50 2016 user.notice preauth: sendind pre-auth
Sat Sep 17 08:00:51 2016 user.notice preauth: sendind pre-auth
Sat Sep 17 08:01:02 2016 user.notice preauth: sendind pre-auth
Sat Sep 17 08:01:02 2016 user.notice preauth: sendind pre-auth
Sat Sep 17 08:01:03 2016 daemon.notice nodogsplash[16434]: Authenticating 10.0.0.79 04:4b:ed:88:3a:2c

this issue is currently more noticeable in Iphone, calling over and over again our remote auth server.
this is normal?

**Comment by mwarning** [comment]
Maybe the phone makes multiple calls? Maybe you can test that.

**Comment by bluewavenet** [comment]
This may be in the realms of Captive Portal Detection. Typically a device will cycle round ssids it knows about and if a captive portal is detected it will move on to the next it can see. It can go round a few times trying to get the strongest signal of 1. closed networks, 2. open, 3. captive - in that order. This all varies from vendor to vendor of course and I have noticed Apple devices doing this more than others, but not terribly so. It usually takes a few cycles/seconds to connect and show the splash page. I have found that on the device you can see it cycling - connect, drop, connect etc. You can make this immediate by either selecting manually the ssid you want or "forget" it on the device then reconnect. This forces the portal detection to stay on the ssid selected rather than cycle round looking for the "best".
There are many implementations of Captive Portal detection and some are better than others. It is evolving rapidly. I am not sure we can do much at the NodogSplash end though.

**Comment by gazambuja** [comment]
I think the best option here (I do this) in /usr/local/bin/preauth make some _cache_ to avoid performance issues.

**Comment by lynxis** [comment]
I guess you're talking about version 0.9 or version 1.0? right. So I'm flagging this to v1.
