### ISSUE TITLE
DNS-tunneling is possible with nodogsplash!

### ISSUE THREAD

**Issue by nihilus** [nodogsplash/nodogsplash#175]
Trying nodogsplash for compatibility reasons with Samsung phones I detected that DNS-tunneling is possible with nodogsplash; it should filter DNS traffic not destinated for 'connectivitycheck.android.com' to avoid people utiltizing DNS-tunnling and remain compability with Samsung's android phones.

**Comment by nihilus** [comment]
Might be a dupe of #73

**Comment by mwarning** [comment]
Only to allow connectivitycheck.android.com will probably leave out non-android devices.

**Comment by nihilus** [comment]
@mwarning Actually this approach works with Linux, Windows, Windows Mobile, BB10, iOS, OS X and Android devices... What more can you expect? ;-)

**Comment by mwarning** [comment]
I do not expect more . :D

But that would need to be tested.
Otherwise users will have a bad time.

**Comment by nihilus** [comment]
Well, let me put it simple; I am reinventing the wheel since nodogsplash etc have faults by design and when doing my IOT I found out about this bug. I would not like if hackers etc used my personal hotspots without having any credentials...

**Comment by bluewavenet** [comment]
Not all Android devices use connectivitycheck.android.com by a long way and even then not all Samsung Androids do either. Apple devices use a wide and ever changing range of CPD URLs, Microsoft devices use numerous and every flavour of Linux I have ever seen uses their own. Yes you could make this work for one particular version of one model of one manufacturer, then it will get its updates and quite probably, will no longer work.

Things I would like to say are:
1. Does it matter if a very few people choose to have an extremely slow connection rather than accept a Hotspot site's terms of service, or logging in etc.? If security is such an issue at a site then there would be NO access at all surely.
2. NDS is not a firewall. "Nodogsplash offers a simple way to provide restricted access to an Internet connection using a captive portal." Being able to tunnel through DNS is not a bug in NDS, more of a problem with DNS.
3. If providing a public hotspot, NDS can easily cover all legal and operational aspects for business or individual providers. These days hackers just need to step outside and connect to the Internet via 3g or 4g etc. Why bother setting up tunnelling?
4. It would be nice to have a simple way to stop DNS tunneling, but no-one has found it.

**Comment by mwarning** [comment]
@bluewavenet thanks for the summary. That is what I suspected.
Fwiw, many hotspots make it possible to tunnel trough DNS (e.g. those used by Deutsche Bahn).

**Comment by nihilus** [comment]
Well there is for sure some more addresses for Android devices however most of them work flawless with a DNS redirect to the portal (which is the most sane to do in preauth state).

For me, personally, selling it as a service it sure matters.

One could agrue that thing A shouldnt do B but starting up NDS with a simple config on my router broke my firewall rules for redirecting DNS and taking care of those issues.

For the 3G/4G stuff I hear you never been to Germany where you really cant buy prepaid dtuff anymore unless you know some insider tricks which I wont tell you.

The simple way to stop DNS tunneling is to DNAT all connections to a DNS daemon which handles the white-/grey-/blacklisting... a generic hint for NDS is to look at ipset and how you can use it, dnsmasq have somr clever ways.

**Comment by bluewavenet** [comment]
@nihilus I think you are missing the point. The primary use I see for NDS is to provide public hotspots in places such as hotels, coffee shops, sports venues etc etc. The owners of these hotspots want to cover themselves legally whilst providing a free service that attracts customers. The cloak and dagger activities of a few hackers are unlikely to effect them in any way.
A simple way of discouraging DNS tunnelling would be to allow only say 10 DNS queries per preautenticated client in 1 minute. The tunnel would the run so slow they would go elsewhere.
Someone would have to write this though. Perhaps it could be put in an enhancement that also includes support for authentication/splash page serving without an Internet connection....

**Comment by nihilus** [comment]
My point is that things should work out of the box withooit having inherited flaws that someone must configure... 

Having 'tc' scheduling DNS requests in preauth would be cool.

**Comment by nihilus** [comment]
Actually they suggest mitigation techniques overe here: https://www.google.se/url?sa=t&source=web&rct=j&url=https://www.sans.org/reading-room/whitepapers/dns/detecting-dns-tunneling-34152&ved=0ahUKEwjD5q6NpcrSAhVCfiwKHVq7AA0QFgggMAI&usg=AFQjCNG4_H6MgL-45Kk1ezYrM5xlTM1-PA

**Comment by nihilus** [comment]
It is a pity I am lazy since there are things needing tinkering on NDS... :-/

**Comment by bluewavenet** [comment]
Well it does work "as intended"  "out of the box". 
A review of defaults is always a good thing and I might muster enough energy to do just that shortly ;)

**Comment by mwarning** [comment]
@nihilus yup, free time is sparse. Merge requests are welcome, of course. But it is beneficial to disuss approaches if a change has a big impact.

**Comment by maxguru** [comment]
The solution is simple: build in 'fake' DNS server that responds with specially crafted messages with low TTL.  Direct all TCP/UDP traffic to port 53 from pre-auth users to this fake DNS server until they authenticate.  Make it so people can get to the splash page with their browser and make other services think there is a temporary network problem so that they keep retrying until the user authenticates using their browser.  Maybe drop connections if non-browser is detected, for example, if MX records are being requested.

This actually touches another problem.  Some services on user's devices may use HTTP to communicate with their API servers.  Serving up splash page HTML instead of expected JSON (or XML or whatever) is not the best idea.  Maybe there should be some kind of human/machine detection.  Using user agent maybe?

Thoughts?

**Comment by mwarning** [comment]
@maxguru not sure about human/machine detection. I see no harm in services getting unexpected input.
Anyway, you can probably already redirect all DNS requests to a web server that answers to all request with the same IP address.
https://github.com/nodogsplash/nodogsplash/wiki/FAQ hast part of the solution using dnsmasq.

**Comment by maxguru** [comment]
@mwarning, interesting.  Still, I feel this should be an integral part of NDS.

**Comment by nihilus** [comment]
@bluewavenet is the issue actually fixed???

**Comment by bluewavenet** [comment]
@nihilus 
The issue is not actually with NDS, but it would be good if NDS could fix the problem with DNS and although some work is slowly being done elsewhere on this, do feel free to contribute :-)
