### ISSUE TITLE
v2.0 n TP-WR841N(d) ? 

### ISSUE THREAD

**Issue by atken** [nodogsplash/nodogsplash#196]
Hi, is a new version compatible on TP-Link WR841N(d), openWrt version 15.05.1?

If yes, could someone please provide build? 

Best regards
Adam

**Comment by bluewavenet** [comment]
The version in CC15.05.1 is very old (0.9_beta9.9.9-5) and broken as far as I can remember.

The latest "built" and released version is 1.0.1-2 and is available with LEDE 17.01.2. This will not run on CC15.05.1 due to kernel dependencies as far as I know. I suggest you reflash with LEDE and go from there. Hopefully version 2 will be available with LEDE soon. ( @mwarning  )

**Comment by mwarning** [comment]
nodogsplash2 should be available in lede trunk now.
For now the package needs to be compiled by hand.
Do https://lede-project.org/docs/guide-developer/quickstart-build-images and select "Network" -> "Captive Portals" -> Nodogsplash2
