### ISSUE TITLE
Question about binVoucher

### ISSUE THREAD

**Issue by ashbenz** [nodogsplash/nodogsplash#213]
Hi all,

Been using nodogsplash (v1) together with sqm and its a nice combo.
Lately I've been experimenting trying to setup binVoucher.

My idea is as follows:
1. Generate a voucher that will have 1 hour of validity.
2. When user tries to login, he's presented with the login page where he enters the voucher generated from step 1.
3. After 1 hour passes, user is kicked out, but can request a new voucher (ie repeat step1).

Now my plan is, to have the voucher generated by a script running on the router itself, so, eg 
http://192.168.1.1/generator.php 
Where the operator (me) clicks "Generate" to issue a new random password to be used as voucher.

Now please help me fully grasp the concept:
The binVoucher can be a shell script, which needs to return: **seconds upspeed downspeed**

Now if I have a php file to generate a random password, how do I then use the generated passwords as vouchers for nodogsplash? I mean how does NDS become aware of the new passwords being generated?

Many thanks!

**Comment by bluewavenet** [comment]
@ashbenz 
First, a couple of problems:
1. Binvoucher does not work properly in V1 and not implemented at all in V2
2. In versions where it does work, the binvoucher speed restrictions are not implemented.

As you have found, SQM works very well with NDS. Even better if you bind it to the interface NDS is using as this gives client/router connection based control, albeit the same for all clients (remembering "upload" and "download" are from the perspective of the router so would need to be reversed in the config).

Having effectively a manual approval, as in your proposal, will rapidly turn into a very arduous task and by experience I would not recommend it. However an automatic bump out is very simple to achieve by setting ForceTimeout to your NDS config.
Instead of using binvoucher, if you implement Forwarding Authentication you can then easily write any authentication method you choose in PHP.
https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service

One final point: The process that detects captive portals in devices, Captive Portal Detection (CPD), is only a de facto standard. Not all implementations by vendors have a polling interval and those that do not will require manual disconnection and reconnection for the CPD to kick in again after being "kicked out". This varies not only from vendor to vendor but version to version as well and is purely a function of the client device operating system with nothing we can do about it in NDS. Having said this, I have not seen this as a problem in numerous large sites as the first thing most people do if they find the connection stops working (in their desperation to be online) is to disconnect and reconnect anyway!

**Comment by isertel** [comment]
Please I need the program... BinVoucher I dont understand th config file

**Comment by bluewavenet** [comment]
@isertel 
It might help to read this:
https://github.com/nodogsplash/nodogsplash/tree/master/forward_authentication_service/FAS-Docs

**Comment by isertel** [comment]
I check this link but the button Accept Terms Of service do not redirect the internet service

**Comment by bluewavenet** [comment]
@isertel 
The logs of the demo server show you are not passing any of the NDS variables, at least I assume it was you as no one has accessed it for a few days.  If you configure exactly as described in the Readme docs it will work. From there you can start writing your own specific version to host on your own server or router.

**Comment by michaeltsengpc** [comment]
Hi 
I've got NDS-FAS working smoothly on the openwrt router. I'd like to control users' internet access by using 'tc'. I've got a tc script working on the router but I 'd like to pass the users' macaddress to the script from FAS(php) and excuse the script with a time control. Does that mean I will need bin voucher function or  if there's another workaround?
Thanks

**Comment by bluewavenet** [comment]
@michaeltsengpc 
If your FAS is running on the nds router, just exec the tc script from php.
If your FAS is running remotely, you have a couple of options.
1. Run an intermediate FAS locally and use it to exec your tc script, either directly on passing through after FAS authentication or by using something like curl or wget from the remote FAS.
2. Wait for NDS version 3 which has new functionality in in the form of Binauth that can be used in conjunction with FAS to run a local script.
Release of version 3 will be in a week or so (from today 9th August 2018) if all goes well.

**Comment by michaeltsengpc** [comment]
Great! looking forward to the version 3!!
Thanks

**Comment by michaeltsengpc** [comment]
Please notify me when version 3 is released and can be obtained from opkg update on openwrt router, thanks!!
