### ISSUE TITLE
Authentication security?

### ISSUE THREAD

**Issue by pruflyos** [nodogsplash/nodogsplash#245]
As far as I understand setting up FAS (Forwarding Authentication Service) doesn't add any real security, because the endpoint `http://192.168.1.1:2050/nodogsplash_auth` doesn't seem to be protected. Anybody can just bypass FAS and authenticate themselves by calling `http://192.168.1.1:2050/nodogsplash_auth?tok=<TOKEN>` using their web browser, curl or wget.

The token value is no secret, because it can be grepped by a `PREAUTHENTICATED` client from the source of the returned splash page:
```
<form method="get" action="http://192.168.1.1:2050/nodogsplash_auth/">
<input name="tok" value="1dd340aa" type="hidden">
<input name="redir" value="" type="hidden">
<input value="Continue" type="submit">
</form>
```
So if I would setup FAS, the action URL would be different, but the `nodogsplash` endpoint would still be wide open. Any technical advanced person who can read source code would find out this endpoint exists and just call it to bypass FAS.

At least I didn't find any configuration to protect the `:2050/nodogsplash_auth` endpoint in any way to prevent users from authenticating themselves. Adding a firewall rule to block port `2050` for `PREAUTHENTICATED` users isn't a solution, because port `2050` is used to serve the splash page as well. 

Would be great if the documentation would highlight that FAS in it's current implementation only protects against non-technical users.

**Comment by bluewavenet** [comment]
@pruflyos 
You are indeed correct. This is purely a function of how NDS implements its simple splash page and is not really an issue with the FAS.

In the majority of installations NDS is used to provide free Internet access through a captive portal, making bypassing a pointless exercise for the vast majority of users.

However with the availability of FAS, much more sophisticated captive portal implementations are possible. Fixing this issue is something on my mind, but time and priorities have prevented me working on it.

An relatively simple modification to NDS would solve this problem. Using a pre-shared key with FAS, NDS could encrypt the token information and serve that in place of $tok. FAS can then, after successful authentication, decrypt and send the actual token back to NDS.

This could be implemented in NDS using OpenSSL or something like Tiny-AES-c
https://github.com/kokke/tiny-AES-c

The additional config options of secure_token enable/disable and the shared key would maintain compatibility with current NDS.

Pull requests are always welcome :-)

**Comment by bluewavenet** [comment]
@pruflyos 
You are not quite reading the implementation correctly. FAS, as in the example, would indeed communicate the decrypted token back to NDS via the client CPD/Browser, but at that point the user will be successfully authenticated so we do not care if they capture it. All tokens are effectively unique, linked to the mac address and time limited in their validity, thus leaving no advantage in passing on to anyone else.
A more sophisticated FAS (the one shown here is only an example/demo) could communicate quite easily, directly with the "endpoint" if so desired although I do not think this is necessary.

> AES is a symmetric cipher and not appropriate for client-side redirects as described.
> 

In this case, why?
All the processing is done on the NDS and FAS server(s). NDS encrypts and sends. FAS receives, asks the client to authenticate and if successful decrypts and sends back to NDS (via the client or not).

> I think the token doesn't need to be encrypted. It should only be signed by the FAS (e.g. using GPG). 

> 
Encrypted or signed?  whatever is the easiest to implement. OpenSSL is usually available for other reasons so AES is very simple to implement and Tiny-AES-c is, well, tiny. I am sure GPG would work too.

**Comment by bluewavenet** [comment]
I might have a go at this at sometime unless anyone else would like to jump in?
