### ISSUE TITLE
Pointers/guide to redirect SSL  (port 443) to splash page 

### ISSUE THREAD

**Issue by ahmed-anas** [nodogsplash/nodogsplash#262]
Hey,
I realize this isn't supported and isn't planned to be supported, however for captive portals, even if a user accesses an https url which is redirect to the splash page, most modern browsers realize that it's a captive portal redirect and allow an https redirect without a warning even when the ssl certificate is invalid. 

So, can someone point me to the relevant code segment or provide points on how/where I should look to allow https/port 443 redirects?

thanks

**Comment by mwarning** [comment]
Nodogsplash uses libmicrohttpd (which supports TLS): https://www.gnu.org/software/libmicrohttpd/
I think you have to modify the code here: https://github.com/nodogsplash/nodogsplash/blob/master/src/gateway.c#L248
But I haven't use libmicrohttpd with TLS support yet.

**Comment by ahmed-anas** [comment]
Thanks @mwarning 

Correct me if I'm wrong, but the code you point to seems to be initializing the web server (which I believe would remain unchanged regardless of which port you redirect from)

I dug a bit into the code and it seems that this is where the redirecting logic is handled: https://github.com/nodogsplash/nodogsplash/blob/55c1164634a7531bb8e24d809ae82a735619492b/src/fw_iptables.c#L441

any ideas?

**Comment by mwarning** [comment]
Hi, I think I misunderstood you.
Yes that is where you direct the https port to the splash page.

**Comment by mwarning** [comment]
Anyway, @bluewavenet started working on something like this yesterday.

**Comment by bluewavenet** [comment]
@ahmed-anas 
> even on https, most modern browsers realize that it's a captive portal redirect and allow an https redirect without a warning even if the ssl certificate is invalid.

Unfortunately that is not how it works for ANY captive portal. All smart devices and most browsers these days have a function called Captive Portal Detection (CPD). There is a lot of discussion of how this works elsewhere on here, but basically the device (or browser) CPD checks for a captive portal by issuing a port 80 request to a dedicated URL provided by the vendor (eg iOS, Android etc.) or the browser (eg Firefox, Chrome etc). It is this that triggers the captive portal's splash page. and gives the impression that https has been redirected when in fact it has not. 
You cannot redirect an https request to the  http splash page without getting "secure connection failed" or "unable to connect". If you provide an https splash page you will get a certificate error always. That is just https working as designed.

There are proposed methods for safely redirecting https but this is not yet implemented in device CPDs or browsers. I am looking into this however, but it is more for a future compatibility rather than anything we can do here. In fact CPD is now very mature, reliable and widely supplied, so this new method if it ever becomes available, will most likely only be of use for reconnects after CP session timeouts thus giving a smoother user experience.

Finally, NDS is fully compatible with all device and browser CPDs.
