### ISSUE TITLE
Authenticated, 404 instead of Status.html

### ISSUE THREAD

**Issue by atken** [nodogsplash/nodogsplash#298]
If I trying to access to NDS Virtual URL or port 2050 after authenticated, 

I'll get 404 instead of **status.html** or in case of **enabled FAS** "status" query to FAS_URL.

In direct access to url:2050/status.html or splash, variables aren't process. 

NDS v3.2.

**Comment by atken** [comment]
Ok now I understand how the Status page is intend. 

I used the Splash page to **automatically** redirect to mine php file by POST and JS with some variables.
And all direct accesses to `http://gatewayaddress` or to missing routes redirected to `:2050,` that served Splash and back to mine php.

I was confused, because it worked for me like that in previous versions.
**That's fine, i'll edit php to get user info from `ndsctl` tool.**

But i want fallback from route `http://gatewayaddress` to some file not redirect to `:2050` with 404.
I personally find it more convenient to display some file (splash, status, redirect to FAS with query status..) instead of 404.

**Comment by bluewavenet** [comment]
> I used the Splash page to automatically redirect to mine php file by POST and JS with some variables.

Be aware that, for security reasons, the Captive Portal Detection process on many client devices will not allow execution of javascript, so it is more or less essential to avoid its use anywhere. It may work with some but does not work with an increasing number of mobile devices.

In normal operation of your captive portal a user should never see the 404 error. It is a general purpose error that means you are asking a server for a resource that does not exist.

I don't understand what you mean by:

> I want fallback from route http://gatewayaddress to some file not redirect to :2050 with 404

Perhaps you could explain what you are trying to achieve?

**Comment by atken** [comment]
First regarding to javascript, do you have some specific devices, which block it? 
I never met with device, that would block javascript in CPD process so far. 

At the moment I trying to get redirect to mine php file, if I'm already authenticated and I access `gatewayaddress`. 

**BTW:**
Didn't you think about implementation FAS option, with clear URL without query (perhaps just redirUrl)?
 For cases, when you use `$_SERVER['REMOTE_ADDR']` to get user IP and `ndsctl` tool to get other info.

**Comment by bluewavenet** [comment]
@atken 
Most CPDs use a very cut down browser by default and are subject to the following general constraints:
* Immediately close the browser when the client has authenticated.
* Prohibit the use of href links.
* Prohibit downloading of external files (including .css and .js).
* Prohibit the execution of javascript.

This varies very much from vendor to vendor and from one version to another, but the trend is a convergence on the above list.

The latest versions of iOS and Android (99.9% of the mobile market) are pretty much there.
Some custom Android versions, notably Samsung, allow the default browser to be changed eg to Firefox or Chrome. Firefox is less stringent, Chrome more so.

As far as javascript is concerned, simple inline scripts will often work eg menu functionality, but little else.  Downloading external libraries or passing variables is not supported.

For any particular vendor/version you may be able to work around these constraints, but as the constraints are there to enhance security, any workarounds are likely to have a short lifetime.

> At the moment I trying to get redirect to mine php file, if I'm already authenticated and I access gatewayaddress.

The simplest way to do this is to set up an index.php page in your FAS at :
`http://gatewayaddress:80/`
You can then add an entry into the hosts file, something simple like "info".
Access your page by using "info" or `http://info.lan`
No redirection required. With openWrt/LEDE 17.xx the hostname is already set to "lede".
in 18.xx it is "openwrt".
In your case typing "lede" or `http://lede.lan` into the browser will show how it works. It will probably take you to Luci if you have left things as default.


> Didn't you think about implementation FAS option, with clear URL without query (perhaps just redirUrl)?

FAS is already very simple, in secure mode, it passes only gatewayname, clientip and redir.
This is the minimum required to identify the CP and client, with the originally requested url added.
Note that FAS can be used either locally or remotely. On a remote FAS, `$_SERVER['REMOTE_ADDR']` will be the upstream address and not the clientip.


>    If the user accesses the splash page when already authenticated, a status page is shown:
>     /etc/nodogsplash/htdocs/status.html
>     In the status.html file, the same variables as in the splash.html site can be used.
> 
> then this is not entirely correct, cause 404 and being served HTML with no variables

This is not worded correctly. It should read "NDS virtual url" rather than "splash page"
I will update this, thanks :-D
