### ISSUE TITLE
different behavior on Android and laptop

### ISSUE THREAD

**Issue by c1p81** [nodogsplash/nodogsplash#313]
Hi,
i'm running NDS on GL.iNet  AR150 with OpenWRT stock firmware.
The opkg package for NDS is 0.9_beta9.9.9-5.
I would like to display an external html page in splash.html and i have an iframe linked to an external website 150.217.xxxx.xxx (to provide a dynamic content without using FAS)

in configuration i have added this line 
  llst preauthenticated_users 'allow tpc port 80 to 150.217.xxx.xxx'

using my laptop i can view the iframe with inside the page from external site
in Android the iframe is blank

i have tried to load only images but same behaviour (i see images on laptop...broken links
in Android)

any suggestions??
it's possible to enable FAS on this version of NDS for OpenWRT ??? What's the syntax?? (i have found tutorial only for DNS 2.x)

Thanks
Luca

**Comment by bluewavenet** [comment]
@c1p81 
First of all, almost all operating systems on both mobile and laptop/desktop now support the defacto  standard Captive Portal Detection (CPD) function designed to facilitate a secure and consistent login to captive portals. This by default uses a cut down browser that is very restricted for security purposes.
What you are seeing on Android is the CPD browser blocking iframes.
On your laptop you will be using your normal browser.

**Comment by c1p81** [comment]
thanks
L.

**Comment by bluewavenet** [comment]
@c1p81 
The AR150 is quite old now and probably coming to the end of production if not already. It is still quite capable though. The Gl-inet factory OpenWrt is stuck at Chaos Calmer probably because no further development is taking place. However it is fully supported in OpenWrt 18.06.1
I suggest you reflash to 18.06.1 although you will loose the Gl-inet proprietary software.
Once upgraded you will be able to install NDS v3.2.1 that has integrated FAS support.
