### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by stevenmunro** [nodogsplash/nodogsplash#355]
I'm attempting to compile the latest version of nodogsplash on ubuntu 18.04 system destined for AR7xxx.

I followed the instructions in the included README.md.

This is the output after running

```
make -j1 V=sc
```

```
make[3]: Entering directory '/data/openwrt/package/nodogsplash'
mkdir -p /data/openwrt/dl
SHELL= flock /data/openwrt/tmp/.nodogsplash-3.3.1.tar.gz.flock -c '     /data/openwrt/scripts/download.pl "/data/openwrt/dl" "nodogsplash-3.3.1.tar.gz" "x" "" "https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/v3.3.1?"    '
Cannot find appropriate hash command, ensure the provided hash is either a MD5 or SHA256 checksum.
Makefile:74: recipe for target '/data/openwrt/dl/nodogsplash-3.3.1.tar.gz' failed
make[3]: *** [/data/openwrt/dl/nodogsplash-3.3.1.tar.gz] Error 255
make[3]: Leaving directory '/data/openwrt/package/nodogsplash'
time: package/nodogsplash/compile#0.15#0.06#0.21
package/Makefile:107: recipe for target 'package/nodogsplash/compile' failed
make[2]: *** [package/nodogsplash/compile] Error 2
make[2]: Leaving directory '/data/openwrt'
package/Makefile:103: recipe for target '/data/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/data/openwrt/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/data/openwrt'
/data/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2
```

I'm making an educated guess that it has something to do with

```
Cannot find appropriate hash command, ensure the provided hash is either a MD5 or SHA256 checksum.
```

But I'd have no idea what so ever in knowing what that means.

**Comment by bluewavenet** [comment]
I am not familiar with compiling on Ubuntu or Debian but does this mean you have not supplied the correct hash to your Makefile?
What is the Makefile you are using?

**Comment by bluewavenet** [comment]
@stevenmunro 
Let us know here if you are still having problems.
Closing for now.

**Comment by zachantre** [comment]
Sorry for reopening the topic. The problem occurs because buildroot cannot download the source file and there is no hash in Makefile. So... here is the solution

download the source tar.gr and put it in openwrt/dl folder
https://codeload.github.com/nodogsplash/nodogsplash/tar.gz/v3.3.1

Edit the Makefile from openwrt/packages/nodogsplash/Makefile and edit the following line from
`PKG_HASH:= #shasum -a 256 of tar.gz of source files goes here`
to
`PKG_HASH:=7480e720136b5945d71ce730e873385ee8ca13dabfc9fb4657a27ec3ae5e7841`

or in case the source is updated, the hash will be different so just use the command
`shasum -a 256 nodogsplash-3.3.1.tar.gz`
and paste the output to PKG_HASH:=

**Comment by bluewavenet** [comment]
@zachantre 
Thanks!

**Comment by stevenmunro** [comment]
@zachantre excellent
