### ISSUE TITLE
Bandwidth and time control

### ISSUE THREAD

**Issue by zachantre** [nodogsplash/nodogsplash#358]
Hello,
I'm trying to modify the nodogspash auth method so clients to generate a voucher code on an Android tablet and use that voucher on their mobiles for one time auth.

So far, I have been able to alter the default fas.php to accept single code and a different php file to generate the code and write it to a fas table.
Everything works fine.

What I cannot figure out is how to implement time limit for the session and the bandwidth control (as in BinAuth).

Is it possible? How can it be done?

Also is it possible to have 2 different time limits? A voucher code to to be valid for 30min and a voucher code for 2h.

**Comment by bluewavenet** [comment]
There are numerous ways to do this as the combination of Fas/Preauth/Binauth gives all the hooks you need. It is all down to your coding inginuity ;-)

Fas (with or without Preauth) and Binauth can be used together.

**Session time limits**
For setting individual session time limits, add a Binauth script that uses your voucher code sent from FAS.

You can use PHP-cli for the Binauth script if you wish.

If you are running FAS locally, AND Binauth scripting in PHP, then if you can use Preauth/FAS to eliminate the need for a separate FAS http server (ie NDS serves your html) - an all round win on a typical resource limited router.

**Data Quotas**
Bandwidth limiting on a client by client basis is not currently supported by NDS, however it is simple to implement quotas using FAS. Make a log of the time a client authenticates - then have a background process that intermittently polls ndsctl for authenticated clients and their data usage, deauthenticating them if their quota is exceeded. If they try to authenticate again, FAS can check to see if they have exceeded their quota for the day before letting them back in. The background process can also be PHP-cli if you wish.

These are some pointers to how to do what you are after using the tools provided by NDS.

**Comment by zachantre** [comment]
by bandwidth control I meant speed limit.
Anyway my scripting skills are non existent... So I would appreciate a little help.

I guess I can enable BinAuth to check if entered voucher code exists in fas table... but I don't really know how to do that.

**Comment by bluewavenet** [comment]
@zachantre you can implement a speed limit for individual users, but this will be the same limit for ALL users.
https://nodogsplashdocs.readthedocs.io/en/stable/faq.html#i-would-like-to-use-qos-or-trafficcontrol-on-openwrt

BinAuth enables post authentication processing, whereas FAS (and Preauth) enables pre authentication processing.

By **authentication,** in this context, I mean the process that NDS uses to allow a client device to access the Internet through the Firewall.

**If we call the "authentication" you do in your FAS code "Credential Verification"** it might make things a bit clearer. (Note to self: worth putting this in the documentation).

In the case you describe, checking the validity of a voucher code is not fundamentally any different to the checking of username and password that is in the example php, so no need to use BinAuth for this.

You can simply add another text input box to fas.php where the user can enter the voucher code they have been given.
The voucher code is then checked against the database.
The username and password can then just be logged, rather than checked.

**Comment by bluewavenet** [comment]
@zachantre 
Closing for now, but please comment if you need any further help.
