### ISSUE TITLE
How to authenticate with a php file?

### ISSUE THREAD

**Issue by DimitrisPr** [nodogsplash/nodogsplash#359]
Hi, 
I am running nogodsplash on Raspberry Pi 3 B+.

**I read the [FAS](https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#overview) docs.** Still, I can't figure out how to redirect the traffic from the splash page to my php page. 

Could you please guide me a little more? I guess I am missing something.

**Comment by bluewavenet** [comment]
The full documentation can be found at:

https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

**Comment by wdeswert** [comment]
I'm sorry to write on a closed issue but I am having the same issue as the author. I am using nodogsplash with a raspberry pi 3 b+ using Raspbian Stretch OS. I have activated FAS to use my index.php splash page located in var/www/html. However, when I connect to the network on my phone it just shows a white screen. Any help would be greatly appreciated.

**Comment by bluewavenet** [comment]
Did NDS work before you enabled FAS?
If you stop NDS can you access your index.php?

**Comment by wdeswert** [comment]
Yes, NDS worked before enabling FAS and yes, I can connect to the index.php via web browser if I disable NDS. I must be doing something wrong or one of the firewall settings is wrong. If you'd like I can send you my nodogsplash.conf file.

**Comment by bluewavenet** [comment]
Which version of NDS?
Yes send the config file.

**Comment by wdeswert** [comment]
Thank you very much for your help, btw :)

I am using version 3.3.0 I believe on Raspbian Stretch latest version

Attached is the nodogsplash.conf file
[NoDogSplashconfig.pdf](https://github.com/nodogsplash/nodogsplash/files/3375688/NoDogSplashconfig.pdf)

**Comment by wdeswert** [comment]
I just did git pull for latest version of nodogsplash and ran it. This time I got the ERR_TOO_MANY_REDIRECTS error.

**Comment by bluewavenet** [comment]
@wdeswert 
You will now be using v3.3.1 if you are getting this error.
The current release is v3.3.2, with v4.0.0 imminent.
Changelog:

nodogsplash (3.3.2)

 * Fix Issue introduced in v3.3.0 with the addition of Improvements towards usable IPv6 support, that caused CPD on client devices to fail with "Too Many Redirects" error. NDS now terminates gracefully with a console error if fasremoteip is not set AND fasport=80 [bluewavenet]
 * Validate fasremoteip to ensure that if it is set, then it is a valid dotted format IPv4 address [bluewavenet]
 * Numerous Documentation updates [bluewavenet]
 * Fix to Known Issue on OpenWrt >18.x.x with v3.3.1. This was caused by misconfigured Makefile for libmicrohttpd; this has been fixed there [bluewavenet]


Your config file has some errors / possible errors.

What is the reason for this line in users_to_router?
`FirewallRule allow tcp port 8000`

`fasport 80` is invalid. Is your FAS running on port 8000?
NDS automatically handles firewall settings for FAS so you do not need to add anything other than the correct fasport.

`GatewayAddress 192.168.50.10` This is not necessarily invalid but GatewayAddress MUST be the ip gateway for the network NDS is controlling. Typically this will be xx.xx.xx.1 or .254.
Autodetection should work fine on Debian variants as well as just about any Linux variant. (the latest documentation will clarify this).

**Comment by wdeswert** [comment]
- How do I check which version of NDS I am using?
- FirewallRule allow tcp port 8000 was set because I changed my Apache port to 8000 as to avoid confusion with NDS (to be clear, I've tried it at port 80 and 8000 with same result)
- Yes, my proper gateway (raspberry pi access point) has the GatewayAddress of 192.168.50.10. I can prove this when I open Chrome browser and type 192.168.50.10:8000 it opens my index.php in the browser successfully.

Any other advice or suggestions would be greatly appreciated. Thank you very much!

**Comment by wdeswert** [comment]
Update: I changed the apache2/ports.conf to make the port 8000. I then set the fasport to 8000. That brought me to a plain white screen without error code (on mobile device or console). Is there an error long I can view on the pi perhaps?

I then set the fasremoteip to 192.168.50.10:8000 and got the following error:
iptables v1.6.0: host/network `192.168.50.10:8000' not found
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.0: host/network `192.168.50.10:8000' not found
Try `iptables -h' or 'iptables --help' for more information.
[3][Wed Jul 10 18:18:43 2019][1677](src/main.c:307) Error initializing firewall rules! Cleaning up
[3][Wed Jul 10 18:18:44 2019][1677](src/main.c:309) Exiting because of error initializing firewall rules

**Comment by bluewavenet** [comment]
* The command to get the NDS version is:
`ndsctl status`

 *  remove:
` FirewallRule allow tcp port 8000`

 * Remove:
`GatewayAddress 192.168.50.10`

 * Set:
`fasport 8000` assuming apache is still on port 8000

Restart NDS then see what happens - look at the system log, /var/log on Rasbian maybe?

**Comment by bluewavenet** [comment]
fasremoteip must NOT be set if FAS is local ( and it must be an ip address if it is set, not ip:port)

**Comment by wdeswert** [comment]
Further update: I am using an Android phone to connect to NDS/FAS and dug around to find this error:

http://192.168.50.10:8000/?clientip=192.168.50.85&gatewayname=NoDogSplash&redir=http%3a%2f%2fconnectivitycheck.gstatic.com%2fgenerate_204

**Comment by bluewavenet** [comment]
Just follow my instructions and try again please.

**Comment by bluewavenet** [comment]
> http://192.168.50.10:8000/?clientip=192.168.50.85&gatewayname=NoDogSplash&redir=http%3a%2f%2fconnectivitycheck.gstatic.com%2fgenerate_204

Why do you think this is an error? It looks like a correct redirect to your FAS to me...

**Comment by wdeswert** [comment]
I agree. After looking into it I agree that it is correctly redirecting to my FAS now. So, thank you!

However, I did everything you suggested and it still takes me to a blank page with the generate_204 message. 

The pi I am using is set up as an access point. So, it is hardwired to my office router (obtaining a 10.0.0.* address for eth0) and creating an AP with gatewayaddress of 192.168.50.10. 

It seems that the issue could either be with my iptables or index.php. I'm guessing that NDS is looking for some sort of authentication to load my index.php (and not getting it which is why the blank page).

**Comment by wdeswert** [comment]
I will let you know that if I disable NDS, open web browser and go to 192.168.50.10:8000 it does open my index.php file. So, there is something with NDS blocking it.

Btw, in case I haven't said it already, thank you 1000 times for your help!!

**Comment by bluewavenet** [comment]
Your FAS (index.php) is supposed to verify the client in the way you choose then it must call back NDS to authenticate. This is described in the documentation.
On redirection to index.php you should see whatever it outputs. Make it simple and have index.php just have:
`echo "hello world ";`
Then you should see that with the:
`http://192.168.50.10:8000/?clientip=192.168.50.85&gatewayname=NoDogSplash&redir=http%3a%2f%2fconnectivitycheck.gstatic.com%2fgenerate_204`

**Comment by bluewavenet** [comment]
Why have you set the LAN interface of your pi to 192.168.50.10?
The pi must be configured as a router with the ethernet as "WAN" and the wireless as "LAN".
The LAN must then provide DHCP  and DNS and default gateway to any connecting devices.
I am assuming this is what you have done? If so why 192.168.50.10? It is probably in its own DHCP range.... Not a problem if you know what you are doing, but why complicate things?

**Comment by bluewavenet** [comment]
All you need is:
 * fasport 8000

**Everything** else at default.

**Comment by wdeswert** [comment]
To be honest, setting up a pi as an access point is all new to me. However, I was able to get it to work...and well. I was also able to get it to work great with NDS when I was just using the splash.html. However, my partner wanted to incorporate iframe into our splash page (as it talks with our server-based control panel for my company) and designed the index.php file to do that. It works great too on its own but just not with NDS so far. 

However, with that said, I did what you suggested of adding echo "hello world"; to the php file and sure enough when I connect now I get a white screen with the words "hello world" :) So, the issue is definitely with our php file not returning authentication credentials back to NDS. 

The main problem now is that we wanted users to be able to see our captive portal first, enter credentials and then be allowed access to the internet. So, I'm re-reading the documentation for NDS to see how that is possible.

**Comment by bluewavenet** [comment]
https://nodogsplashdocs.readthedocs.io/en/latest/

**Comment by wdeswert** [comment]
Yep, reading that now :) Seeing that preauth might be what I need to set up now.

**Comment by bluewavenet** [comment]
Note: the client CPD will block iframes as well as javascript as these are security risks in a captive portal. This is the client device that does this, not NDS.

Try the preinstalled preauth script. Setting ONLY the parameters set out in the config.
