### ISSUE TITLE
CPD not working as expected

### ISSUE THREAD

**Issue by eduperez** [nodogsplash/nodogsplash#363]
I have installed NDS on my OpenWrt router. With the default configuration, it is working mostly as expected, except for an issue.

My devices detect the redirection when they first connect to the network, but when the authorization expires, they no longer display the splash screen, but just announce that there is no internet connection. I have to make them "forget" the wireless network, then introduce the password again, but this is not practical.

Is this how is it supposed to work? Or did I miss something? Thanks!

**Comment by bluewavenet** [comment]
@eduperez  A little background to put things into perspective:

Captive Portal Detection was, as far as I am aware, initially implemented by Google a few years ago. It has evolved and matured and been implemented on just about every platform, including most browsers since then.

It is important to remember that it is designed primarily for mobile devices to automatically detect the presence of a portal and to trigger the login page, without having to resort to breaking SSL/TLS security by requiring the portal to redirect port 443 for example.

Just about all current CPD implementations work very well but some compromises are necessary depending on the application.

The vast majority of devices attaching to a typical Captive Portal are mobile devices.
As you have seen, CPD works well giving you the initial login page.

For a typical guest wifi, eg a coffee shop, bar, club, hotel etc., a device connects, the Internet is accessed for a while, then the user takes the device out of range.

When taken out of range, a typical mobile device begins periodically polling the wireless spectrum for SSIDs that it knows about to try to obtain a connection again, subject to timeouts to preserve battery life. 

Most Captive Portals have a session duration limit (NDS included).

If a previously logged in device returns to within the coverage of the portal, the previously used SSID is recognised and CPD is triggered and tests for an Internet connection in the normal way. Within the session duration limit of the portal, the Internet connection will be established, if the session has expired, the splash page will be displayed again.

Early mobile device implementations of CPD used to poll their detection URL at regular intervals, typically around 30 to 300 seconds. This will trigger the Portal splash page quite quickly if the device stays in range and the session limit is reached, preventing the problem you are seeing.

However it was very quickly realised that this polling kept the wifi on the device enabled continuously having a very negative effect on battery life, so this polling whilst connected was either increased to a very long interval or removed all together, depending on vendor, to preserve battery charge. As most mobile devices come and go into and out of range, this is not an issue.

However if the device stays within range, without CPD polling, until the session expires, the issue you are seeing appears.

The workaround you have found, or even just manually disconnecting or turning wifi off or on will simulate a "going out of range", initialising an immediate trigger of the CPD. One or any combination of these workarounds should work, again depending on the particular vendor's implementation of CPD.

In contrast, most laptop/desktop operating systems, and browser versions for these still implement CPD polling whilst online as battery considerations are not so important.

For example, Gnome desktop has its own built in CPD browser with a default interval of 300 seconds.
Firefox also defaults to something like 300 seconds.
Windows 10 is similar.

So in answer to your question, this IS how it is supposed to work, but does involve some compromises.

The best solution is to set the session timeout to a value greater than the expected length of time a client device is likely to be present. My own experience shows a limit of 24 hours covers most situations eg bars, clubs, coffee shops, motels etc. If for example an hotel has guests regularly staying for a few days, then increase the session timeout as required.

Staff at the venue could have their devices added to the Trusted List if appropriate, but, again in my experience, it is better not to do this as they very soon learn what to do and can help guests who encounter the issue. (Anything that reduces support calls is good!)

**Comment by mwarning** [comment]
@eduperez yes, that is how it is supposed to work.

**Comment by eduperez** [comment]
@bluewavenet Many thanks for the long and detailed explanation, I really appreciate the effort you put there. So, I understand that NDS and CPD are both working as expected, and all this makes sense now.

**Comment by bluewavenet** [comment]
@eduperez @mwarning  It is a common situation and I had actually written most of my reply previously but not posted anywhere.
I have now added this to the NDS Wiki :-D

https://github.com/nodogsplash/nodogsplash/wiki/2-FAQ
