### ISSUE TITLE
how to pass clientMAC and gatewayMAC as GET variables.   Node.js

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#382]
this is not a new question but I really had to asked. I tried  to pass clientMAC and GatewayMAC to my _express.js_ application as GET variable what is the way to do it

**Comment by bluewavenet** [comment]
@bawantha 
In the default simple splash page (splash.html) clientmac is passed as a template variable $clientmac.
In FAS with security switched off, it is passed in the query string to FAS.
Otherwise FAS must obtain this along with the client token using ndsctl.
In the soon to be released v4.0.0, NDS passes gatewayname, clientmac and the token in an encrypted form in the query string.

Gatewaymac has not been available for some time as a template variable and is not reported by ndsctl. It was of no real use as it is after all just the mac of the interface NDS is serving.

Gatewayname is intended for identification and is particularly useful for a shared remote FAS for identifying which instance of NDS the request is coming from.

Bare in mind that many variations of client CPD prohibit the use of javascript as this is a particularly bad security issue for a captive portal. If you are using node on your FAS server though, it will be ok as long as you do not depend on any execution of js on the client.

**Comment by bawantha** [comment]
@bluewavenet 
Thanks for your reply,
but I couldn't find clientmac as query string in FAS ( when security switched off ), what I really don't understand is how we get clientmac ( etc. ) with **token** ( yeah I can get token as query string ) using **ndsctl** what is **ndsctl** any example for use of **ndsctl**  for such a scenario ? 
Thank you.

**Comment by bawantha** [comment]
@bluewavenet 
Hi I went through Doc and found this [https://nodogsplashdocs.readthedocs.io/en/stable/ndsctl.html](url) but I cannot get an idea about how to use it could you please guide me to example ?

**Comment by bluewavenet** [comment]
@bawantha 
Apologies, my mistake, clientmac is not sent even with security set to 0. 
This is because exposing the client mac in clear text is a security concern. In addition any client verification would normally be at the user level, not the client hardware level so it is generally not needed for basic FAS verification.

Using ndsctl to obtain it must be done locally to NDS so is difficult for a non local FAS, but not impossible.

However this difficulty has been mitigated entirely in NDS version 4.

I have no experience with node, node/express so cannot help you there, but if you let me know some details of your setup I can certainly give you some pointers in the right direction:

1. Hardware, OS and OS/version running NDS (edit: just saw your previous post)
2. Version of NDS
3. Location of your FAS (ie on the NDS router, on a machine on the NDS LAN or on a hosting server on the Internet)

I very much suspect everything will be much easier if you were to use NDS v4.
This is now released (but not available yet as a binary from OpenWrt downloads).
https://github.com/nodogsplash/nodogsplash/releases/tag/v4.0.0

And new documentation:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#security

**Comment by bawantha** [comment]
#386 here I have shown what is my network diagram
