### ISSUE TITLE
NDS v4 , faskey enable not working.

### ISSUE THREAD

**Issue by bawantha** [nodogsplash/nodogsplash#386]
Hi
In NDS v4, by enabling faskey CPD not working splash page won't pop up and able to access internet without intercepting ? , every thing went okay until enable faskey.
Thank you.

**Comment by bluewavenet** [comment]
@bawantha 
there are additional configuration requirements.
Check logread just after starting nodogsplash.
ie the following commands in a console:
```
service nodogsplash restart
logread
```

**Comment by bluewavenet** [comment]
Documentation for fas_secure_enable=2 at:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#security

**Comment by bluewavenet** [comment]
Typically, you will need to install php7-cli  and php7-mod-openssl. eg:

```
opkg update
opkg install php7-cli
opkg install php7-mod-openssl
```

**Comment by bawantha** [comment]
@bluewavenet those packages are not available

**Comment by bluewavenet** [comment]
@bawantha 
There were a lot of failures in OpenWrt snapshot packages on the last build cycle so yes they are missing at the moment unfortunately. Snapshot is like that sometimes - patience required I'm afraid.

**Comment by bawantha** [comment]
Hay take a look at my [network diagram]([url](https://imgur.com/a/dyFxuhz)) even using PHP how can execute 

> `$clientmac = exec("sudo /usr/bin/ndsctl json ".$clientip." | grep mac | cut -c 8- | cut -c -17");` 

from remote server to router IS IT POSSIBLE??

**Comment by bluewavenet** [comment]
@bawantha 
Just today, on the aarch64_cortex-a53 architecture, openssl has started to fail to compile for some reason on Openwrt Snapshot. As both php7 and Node depend on openssl, both these are also failing to compile. It seems ok on other architectures though. You will just have to be patient. You could report it on https://bugs.openwrt.org/ and see what happens.
It will most likely be ok again tomorrow, you will have to check.
It is a problem with using Snapshot.
Alternatively you could use a low cost mini router (probably cheaper than a pi3 and definitely better at being a router - the Pi hardware is good for running software but not good at network routing due to i/o bottlenecks and the chipsets used). 

> from remote server to router IS IT POSSIBLE??

Yes it is possible to communicate with NDS from outside on the Internet as in your diagram.
But this cannot be built in to NDS in a sensible way, it is up to developers like yourself to use available tools to set something up.

**A hint:**
_Set up a web page on your NDS router and allow access to it from the Internet through your firewalls using port forwarding.
Your external server can then call this page using wget or curl, requesting whatever information you need (eg client token, client mac) by providing the client ip address that is sent in the query string._

NDS v4 makes all this redundant however, by adding faskey, fasremotefqdn and fas_secure_enable=2, enabling NDS to send the required information in an encrypted form even to a shared hosting service without having to know specific details of the hosting type.
