### ISSUE TITLE
Document in RTFD.io need some updates

### ISSUE THREAD

**Issue by kmahyyg** [nodogsplash/nodogsplash#455]
I've tried to build the debian package by myself on my Rpi4B, but as I'm following the document in rtfd.io, I just switch to repository root and type `dpkg-buildpackage`, then it failed immediately, said that `can't build with source format '3.0 (quilt)': no upstream tarball found at ../nodogsplash_4.3.2.orig.tar.{bz2,gz,lzma,xz}`.

After I check a closed issue, I think I found the answer is `make deb` instead.

Please update document to avoid misleading for new end users.

**Comment by bluewavenet** [comment]
@kmahyyg 
Thankyou for pointing this out.
Unfortunately the mainstream development recently has been done on Openwrt (by me) and I do not use Debian. The documentation for Debian has not changed since originally created as far as I am aware so should indeed be updated. Pull Requests welcome ;-)

The section "Installing on Debian" needs rewriting:
https://nodogsplashdocs.readthedocs.io/en/stable/install.html#debian

The section "How to Compile" also needs some work although it is to create the binaries rather than a specific disto's package:
https://nodogsplashdocs.readthedocs.io/en/stable/compile.html#linux-unix

Can you verify `make deb` works as intended?

**Comment by kmahyyg** [comment]
I can confirm that this deb package is successfully built and packaged, but I can’t ensure it work properly since I’m using this software first time and still need some time to try to manage it.

I compiled it on raspbian buster,  but my main OS is Arch Linux, I’ll try to file a PR after I’ve done my job using nodogsplash.
