### ISSUE TITLE
Is it possible to have html form button with two actions on splash.html?

### ISSUE THREAD

**Issue by wdeswert** [nodogsplash/nodogsplash#456]
I am using nodogsplash as a captive portal. Everything is default settings in that I am using /etc/nodogsplash/htdocs/splash.html on port 2050 as my landing page. I have added an HTML form (which has three text input boxes) and "Sign In" button into splash.html and have given the button the included authorization code:

<form method="get" action="$authaction">
                                    <input type="hidden" name="tok" value="$tok">
                                    <input type="hidden" name="redir" value="$redir">
                                    <input style="background:#0073c3;color: white;" type="submit" value="Sign In">
                                </form>

This works perfectly fine on its own. However, is there anyway to add a second action to this same button? I want to send the information collected in this form's text input boxes as an email. 

Thank you very much in advance for your help.

**Comment by bluewavenet** [comment]
@wdeswert 
splash.html is a simple templated page with limited/fixed variables, so the short answer is no.

To have complete flexibility in your captive portal page you should use the FAS option. This will allow you to write your own fully dynamic portal that can have as many input variables and forms as you wish, even conducting a dialogue with the client.
From version 4.3.0 onwards a basic FAS Preauth script is ready installed and is enabled by setting config option login_option_enabled to “1”
This example is written in shell script but could be written in any scripting language such as php or python if you wish.
Other examples written in php are available that can even be hosted on a centralised server as well as locally.
See the documentation at:
https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html
and
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html

Feel free to ask any questions.

**Comment by wdeswert** [comment]
Thank you for the info, Rob. I really appreciate it. I looked over everything and had one more question.

Based on what I read I should be able to use splash.html along with php if I use FAS and set our files to use a different port/location (for example port 80 at /var/www/html) as long as we have our script return at least $tok back to the url in $authaction. Does this sound accurate?

**Comment by bluewavenet** [comment]
@wdeswert
Sorry, no, you are misunderstanding how FAS works. NDS redirects to a script or executable programme that dynamically generates html and serves it to the client either with the NDS built in web server or an independent web server. Splash.html is not used at all.
Share some detail of your set up so I can have a better understanding of what you are trying to achive and I can then give you some hints.
I suggest you try the included example scripts to get a feel for how it works.  Enabling the preinstalled fas/preauth script to give you username/emailaddress login will be a good start. The path to the script so you can see how it is written, is:
`/usr/lib/nodogsplash/login.sh`

**Comment by wdeswert** [comment]
My current situation is that I have set up NDS to act as a landing page/captive portal on a raspberry pi 3b+, using the default configuration of using splash.html in /etc/nodogsplash/htdocs. On our splash.html (which is our own custom design that we renamed splash.html) we have a form which includes text input boxes and a sign in button. When the sign in button is pressed, I want the information in the text boxes to be emailed to me, while simultaneously giving the user authorization through NDS. So far, I can only get the user to be authorized but can't figure out how to also send the email.

Thank you in advance for all of your help!

**Comment by bluewavenet** [comment]
Are you using Raspbian, Openwrt or something else?

Which version of NDS do you have? Current version at the time of writing is 4.3.2 for Debian variants.

NDS has two basic means of interacting with clients:
 * Templated html (aka splash.html)
 * Forwarding Authentication (aka FAS)

Templated html is simple and easy to use. However supports only a very limited and fixed number of variables. It is designed to serve a trivial "Click to Continue" interface and not much more.

FAS can do whatever your programming abilities will allow (subject to CPD limitations).

The pre-installed FAS/PreAuth login script already does most of what you are trying to do. All you would need is to modify the script slightly to use an email client package to send the email.

As I suggested earlier, you really need to read the full documentation to get a proper understanding of how it all operates, then try the login script option.

It is possible to extend the Templated html slightly to accept username and password using BinAuth, and an example script can be found in the source code, but if you are trying to do any more than this (and you are) you will have to use FAS. (BinAuth is normally used for post authentication processing in combination with FAS)

Finally, if this is an academic project using existing hardware then the Rpi is just fine, but for a serious project intended for production, dedicated router hardware would be a much better choice. This is because the built in networking on the Rpi is designed only for station use and does not make a very good router.

**Comment by wdeswert** [comment]
Hello!

Well, some good news is I was able to make it work. Thank you for all of your help. I am still using splash.html in /etc/nodogsplash/htdocs. 

However, I now have another problem/question. Everything works great except that the embedded mp4 videos on my splash.html page do not play on Apple products. Yes, the videos play fine on the Apple products if I put them in /var/www/html and navigate to them via safari. So, there is an issue streaming the mp4 files through NDS but just on apple products. 

Any ideas?

**Comment by bluewavenet** [comment]
This is a function of the client CPD. 
CPD is software running on the client device, supplied by the vendor and outside the control of any outside influence. Most vendors have their own implementation of CPD and most will block anything but simple html for security reasons.
The non-apple device(s) you have tested with may well stream mp4 "currently" but you will most likely find after a client update they will not. CPD has been rapidly developing over the last few years and the developers are very quick to fix potential security issues - streaming an mp4 automatically just because the client connected to a public wifi is certainly a potential security risk.
