### ISSUE TITLE
Preauth scripts issue

### ISSUE THREAD

**Issue by skullfisher87** [nodogsplash/nodogsplash#460]
Hello. 
Firts i want to state that i readed all the ndg official and non official documentation. 

Im runnin versión 4.3.0. 

I want to call an External image so i downloaded the demo scripts, copy them into the  etc/nodogsplash/  
Then i want to call the scripts enabling and changin the path on the config file but this Is not working at all. No Splash page i can use internet without going trought ndg.

So basically im missing something here and the custom External banner demo from the official guide is not clear. Would be better  step by step guide for dummies.

Again. Im nota lazy, i read everything outthere about ndg and also spend days reading the scripts and codes To take a better understunding. This Is why i ask here for help.

Kind regards.

**Comment by bluewavenet** [comment]
@skullfisher87 
You are very welcome to ask questions. Feedback is always useful.

First, it is very important for you to state:
 * your operating system
 * your operating system version
 * your hardware and any options installed
 * the version of NDS you are using (thanks you did state this)
 * did NDS work before you made ANY changes?

Note: The current version at the time of writing is 4.3.3 and I will probably ask you to upgrade to this if possible before continuing.

**Comment by skullfisher87** [comment]
@bluewavenet  
Hi Rob, tnx for your kind words. 

My system spects:

- OS Windows7 home basic SP1  x64

The AP where i installed openwrt:

- TP-Link CPE210 v3   -  SNAPSHOT, r10250-016d1eb
 
- Is clean install, i just downloaded the snapshot for my CPE, i didnt made any image myself.
-
- The only thing i installed into openwrt is NDG and i followed the official guide steps trought CLI

- opkg update and then opkg install nodogsplash (last thing i done today is remove it and reinstall to upgrade to 4.3.3 but it installed agian the 4.3.0 ).

NDS works perfectly before any change.  While im trying to run the preauth scripts it dosnt work.. only the preauth login script.

As i stated before when i try to run the demo external script from  the example on the guide it just dont work.


What I try to do with NDG is basically call and external banner of myself. Another option wich im trying now is call my portal web page trought and iframe but i dont know really how ty bypass it from the firewall.

I want people to click my banner to basically monetize my hospot on this way.


Im pretty newbie here, also my native lenguage is spanish. I will be glad to translate the official guide or make a tutorial for my native speakers if i get this done.

**Comment by bluewavenet** [comment]
@skullfisher87 
First, off topic for a second - Don't try going down the iframe route, it won't work properly. Client devices all use their own versions of CPD, and most if not all CPD implementations will either block iframes, prevent downloads, block external links etc. This is required for security as a unscrupulous captive portal owner could otherwise trick a client user into thinking they were connected to something else.

Back on topic - you say the default “Username/Email-address” Login script works when enabled?
ie in the uci config file (/etc/config/nodogsplash):

`option login_option_enabled = ‘1’`

If so then all is well with NDS.

A quick way to enable this is to run the following commands on a router terminal:

```
uci set nodogsplash.@nodogsplash[0].option login_option_enabled = ‘1’
uci commit nodogsplash
```

If you run (on the router) the command:

`service nodogsplash restart`

followed by:

`logread`

then you will see the NDS startup messages showing that all is well. 

The next step is to replace the included “Username/Email-address” Login script with the demo-preauth-remote-image.sh script.
The quickest "beginners" way is to delete the /usr/lib/nodogsplash/login.sh file, copy the demo-preauth-remote-image.sh and rename to login.sh

The final step is to make sure the new script is executable.
The following command will do this:
`chmod u+x /usr/lib/nodogsplash/login.sh`

Then restart NDS and check for errors:
```
service nodogsplash restart
logread
```

After this, a connecting client should see the NoDogSplash Bulldog Avatar instead of the splash.jpg on the login page.

The final point is that version 4.3.3 should really be used as 4.3.0 has an issue that can cause NDS to spontaneously restart under high load.

NDS 4.3.3 is the current version in snapshot mips_24kc. You should be getting this after 
`opkg update`
Check if it is returning any errors, it will error if it cannot see the online repositories.

My final point - the CPE210 - as it only has 8MB Flash and 64MB ram, it is not suitable for any kind of more sophisticated LOCAL FAS. It will however work well with a remotely hosted FAS if set up to use fas secure level 1 with hash_id (hid), but first lets move you on from "newbie" status ;-)

**Comment by skullfisher87** [comment]
Ok. Here is what i got.

Firts i sucefully upgraded to versions 4.3.3 (i really dont know why because i made the same steps that i tried before).

I manually changed to option loging_option_enabled = '1'         //The uci command didnt work. also where can i find this commands ? i want to learn.

Manually replaced and renamed the demo script to login.sh  , also made the chmod command and logread - firts time didnt work as i got a non executable script but i start again from clean installation and then it worked.

Finally i restarted ndg again and the script loaded the splash page but i cant see the mad wifidog avatar, is like the link is broken but i copied the image link from the script (https://avatars0.githubusercontent.com/u/4403602) and sucefully load but not from the splashpage.

So is a weird thing, guess something is preventing it to load. Wonder how can i find the error. I got a 404 error from the browser console.

Here i leave a screen showing the issue :

![image](https://user-images.githubusercontent.com/56849408/67450477-ed622100-f5f3-11e9-8a49-9323d2ff94e7.png)

**Comment by skullfisher87** [comment]
> uci set nodogsplash.@nodogsplash[0].login_option_enabled='1'
> 
> The command is run as root, from an SSH terminal window.

I mean where can i find the information about this commands. I want to learn.

> i cant see the nodogsplash avatar,
> 
> I got a 404 error from the browser console.
> 
> If you use your Windows browser to manually go to the NDS page, for example:
> http://192.168.1.1:2050
> then you will see exactly these symptoms. I am guessing that this is what you are doing.

What i do is acting like a normal wifi guess to see what happend. im not manually going to the ip adress. 


Anyway, guess im gonna read more about how CPD's works so i know what can and what cant i do with captive portal solutions. My wish is implement somehow a cryptocurrency mining option like JSEcoin to monetize my hospot. i.e I made this web ---> portal.bariloche.site  

For more info you can go to www.jsecoin.com  is very interesting. 

I read somewhere that CPDs closes after authentication but you cant prevent this with some DNS and walled garden config but that is a next step.

Gonna try my actual config at my office and see what happend, so see you tomorrow.


Again, tnx for your time i really apreciate it.

**Comment by bluewavenet** [comment]
@skullfisher87 
I found the problem! It is my fault, I forgot to update the documentation after all the changes in the last few releases - oops!

**Summary:**
If the remote image is served from an https site, ssl/tls support for wget is required.

**Fix on OpenWrt:**
Install the packages:
 * libustream-mbedtls
 * ca-bundle

**Comment by bluewavenet** [comment]
@skullfisher87 

> I mean where can i find the information about this commands. I want to learn.

https://openwrt.org/docs/guide-user/base-system/uci

With regard to CPD, it is designed to provide a pop up captive portal login screen, with security given a very high priority.
The CPD browser found on up to date mobile devices is very restricted for those security reasons, otherwise an unscrupulous captive portal could pretend it is some other web page, install software etc. 
The main restrictions found in most up to date CPD implementations are:
 * Download of any files to the client is prohibited 
 * Running javascript is prohibited (with some minor html5 related exceptions)
 * Certain html commands are prohibited (eg iframes)
 * CPD browser will close automatically when Internet access is detected.

There have been various hacks to get round this, but as the main developers of CPD are Apple and Google, any new vulnerabilities that are found are rapidly fixed.

**Comment by bluewavenet** [comment]
@skullfisher87 
Closing issue as fixed but please feel free to report back or ask any questions
