### ISSUE TITLE
How to enable the upload and download settings of traffic control?

### ISSUE THREAD

**Issue by openwrt-diy** [nodogsplash/nodogsplash#467]
How to set the upload and download parameter values of traffic control through UCI?
The commands I am using now are as follows:

uci set nodogsplash.@nodogsplash[0].trafficcontrol=1
uci set nodogsplash.@nodogsplash[0].downloadlimit=512 ###Parameter is invalid
uci set nodogsplash.@nodogsplash[0].uploadlimit=128 ###Parameter is invalid
uci commit nodogsplash
Service nodogsplash restart

When compiling openwrt-4.14.149 and nodogsplash-4.3.3 firmware, iptables-mod-imq, kmod-ipt-imq has been successfully integrated.

**Comment by openwrt-diy** [comment]
/$ ndsctl status
==================
NoDogSplash Status
====
Version: 4.3.3
Uptime: 1m 12s
Gateway Name: OpenWrt Nodogsplash
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.200.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Disabled
Client Check Interval: 600s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Traffic control: yes
Download rate limit: none
Upload rate limit: none
Total download: 1052 kByte; avg: 116.97 kbit/s
Total upload: 174 kByte; avg: 19.40 kbit/s
====
Client authentications since start: 1
Current clients: 1

Client 0
  IP: 192.168.200.181 MAC: e0:d5:5e:25:49:0d
  Last Activity: Fri Nov 01 15:24:33 2019 (0s ago)
  Session Start: Fri Nov 01 15:24:17 2019 (16s ago)
  Session End:   Sat Nov 02 11:24:17 2019 (19h 59m 44s left)
  Token: 0e39b4e6
  State: Authenticated
  Download: 1029 kByte; avg: 514.52 kbit/s
  Upload:   100 kByte; avg: 50.35 kbit/s

====
Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none
========

**Comment by bluewavenet** [comment]
@openwrt-diy 
Integrated traffic control has been unavailable since OpenWrt 12.09 (Attitude Adjustment) when IMQ support was removed from the kernel.
Traffic shaping is now available using the SQM - Smart Queue Management (sqm-scripts) package. See the documentation at:
https://nodogsplashdocs.readthedocs.io/en/stable/traffic.html

It is intended at some time to re-integrate traffic control into NDS (although at a very low priority) and as you have found, the undocumented option

> uci set nodogsplash.@nodogsplash[0].trafficcontrol=1

is accepted but has no function. Admittedly this is slightly confusing if you have not read the latest documentation.

**Comment by openwrt-diy** [comment]
The sqm setting of the document is br LAN,Sqm for wired AP and wireless bridge relay need how to set,？these two schemes use more people!

**Comment by bluewavenet** [comment]
You should configure SQM to use the interface NDS is controlling.
eg.
`uci set sqm.@queue[0].interface='[your_nds_interface]'`
