### ISSUE TITLE
Cannot use ndsctl status, clients or json within a Binauth script

### ISSUE THREAD

**Issue by garciave** [nodogsplash/nodogsplash#503]
Hi,

I tried in several ways to get the json response from a newly authorized client or just deauthorized client, trying to run ndsctl json macaddress (getting the mac_address from $2) and whenever the program gets into this line, the system halts. If you try to run from command line ndsctl status, it will be no response.

I am using nds version 4.0.1 on a Raspberry PI 3B+ running OpenWRT 19.07.0.

I am just running a binauth script running:
output=$(ndsctl json $2)
echo $output >> /root/l.json

within the "client_auth" or "idle_auth" event. Once the line output=$(ndsctl json $2) is reached, the system stops.

BTW, the only objective is to get the token associated to the mac address of the client being deauth'd; is there any way to get it rather than running the ndsctl json command?

Tks,
Oscar

**Comment by garciave** [comment]
Just another comment to be clear, if I run the same commands from cli, they work correctly. The problem it's only happening when run from inside the binauth script.
Tks!

**Comment by bluewavenet** [comment]
@garciave 
I don't know what is in your binauth script, but it needs to end at least with something like:
```
echo 0 0 0
exit 0
```
otherwise NDS will just hang waiting for a response from the script.

**I would however recommend  upgrading to at least NDS to version 4.4.0**, the current release at time of writing, as there have been many enhancements and bug fixes since v4.0.1.

For the rpi 3 series:
https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/routing/nodogsplash_4.4.0-1_aarch64_cortex-a53.ipk

The most important fix for you is the **bug in ndsctl v4.0.1** which causes a deadlock if more than one instance of ndsctl is run concurrently. This is unlikely to be the issue here though as you are probably testing with one client at a time.

Version 4.4.0 contains numerous installed library scripts plus numerous example binauth, preauth and fas example scripts in the source code.

These scripts are enhanced even further in v4.4.1beta in master, including the script `get_client_token.sh`
https://github.com/nodogsplash/nodogsplash/blob/master/forward_authentication_service/libs/get_client_token.sh

The source code contains the script `binauth_log.sh`. This provides a full working binauth that produces a log of all client authentications. Adding a call to get_client_token.sh is all you would need ;-)
https://github.com/nodogsplash/nodogsplash/blob/master/forward_authentication_service/binauth/binauth_log.sh

**Comment by bluewavenet** [comment]
@garciave 
I have updated the documentation for get_client_token
https://nodogsplashdocs.readthedocs.io/en/latest/libraries.html#list-of-library-utilities

**Comment by garciave** [comment]
Tks a lot for the response.

I was already using the exit 0. My code in binauth is super simple:
#!/bin/sh

# Get the current Date/Time for the log
date=$(date)

action=$1
clientmac=$2

if [ $action == "auth_client" ]; then
   clientmac=$2
   ndsctl allow $clientmac
   # Append to the log.
   echo "Auth requested: $date, method=$1, clientmac=$2" >> /root/actions.log
fi

if [ $action == "client_auth" ]; then
   clientmac=$2
   redir_enc=$5
   redir=$(printf "${redir_enc//%/\\x}")
   useragent_enc=$6
   useragent=$(printf "${useragent_enc//%/\\x}")
   # Append to the log.
   echo "Auth granted:  $date, method=$action, clientmac=$clientmac, clientip=$7, username=$3, password=$4, redir=$redir, useragent=$useragent" >> /root/actions.log
   output=$(ndsctl json $2)
   echo $output >> /root/l.json
fi

if [ $action == "idle_deauth" ] || [ $action == "client_deauth" ]; then
   output=$(ndsctl json $2)
   echo $output >> /root/l.json
   # Append to the log.
   echo "Auth drop:  $date, method=$action, clientmac=$2, bytes_incoming=$3, bytes_outgoing=$4, session_start=$5, session_end=$6" >> /root/actions.log
fi

exit 0

When the program gets to the json line, it simply stops. Hope you might reproduce it.


Then I also tried to parse the json using:
client_token=$(ndsctl json $clientip | awk -F '"' '$2=="token"{printf $4}')
but also hangs... so not sure what it's happening.



Finally, I uninstalled the old version and tried to install the 4.4.0 that you provided me the link but it does not even gets installed. I got the following error:
root@OpenWrt:~# opkg install nodogsplash_4.4.0-1_aarch64_cortex-a53.ipk
Installing nodogsplash (4.4.0-1) to root...
Configuring nodogsplash.
uci: Parse error (invalid command) at line 22, byte 8

Not sure if there is a snapshot version issue as I am using a Raspberry PI 3 B+. I had installed the v4.0.1 via Luci so I am not sure if the package should be aarch64_cortex-a53 or another.

Tks

**Comment by bluewavenet** [comment]
@garciave 
I think you found a "bug" or at least a restriction. It seems you cannot run ndsctl status, clients or json from a binauth script. I have not had time to look at the code but I suspect some kind of deadlock. I will investigate!

However, the client token is of little or no use to binauth and is not information of any use in a log. This is why it is not passed to binauth by NDS... unless you can convince me otherwise :-D

Ndsctl apart, your script has the arguments wrong.

For "auth_client", NDS supplies the following arguments:
$1=method (=auth_client in this case)
$2=clientmac
$3=username
$4=password
$5=redir
$6=useragent
$7=clientip

NDS supplies all other methods with the arguments:
$1=method
$2=clientmac
$3=bytes_incoming
$4=bytes_outgoing
$5=session_start
$6=session_end

`uci: Parse error (invalid command) at line 22, byte 8`
I don't know where that comes from, but my guess is you have an invalid config file...
v4.4.0 works fine here.

The PI 3 series are all aarch64_cortex-a53 as far as I know.

**Comment by garciave** [comment]
Hi, I believe it might be a bug. 
Not sure if I'll be able to convince you :-) but just want to have an unique identifier for the given session. Perhaps the token is not the most appropriate field but it's the only one I could think about it.
What I want is a way to have a unique record in a db table to keep track of all sessions that client_auth method might insert and then the deauth methods (any of them) could update with the arguments you mentioned. I could try to set a query looking for the mac address and other fields  to make this work but if there is already a unique identifier, it will be x times better.
If you believe it might be a different approach, glad to hear.

For the PI3 and the v4.4.0, I will probably set it in a brand new OpenWRT install and check. You might be right about the config file. If it works on your end, it will as well on mine.

Tks

**Comment by garciave** [comment]
@bluewavenet 
As another detail, in case it's of any relevance when you look in the code, I am using FAS with a remote server. Cheers

**Comment by bluewavenet** [comment]
@garciave 

> What I want is a way to have a unique record in a db table

Then generate a random number.... That is all the token is after all.

> I am using FAS with a remote server

In that case, FAS knows either $tok or $hid depending on fas secure level.

You can pass $tok or $hid to binauth in various ways. Probably the simplest way is to populate either of the username or password variables, or if you are using them already, then append to username with a suitable separator so your binauth can extract it.
eg to populate password, do this in your FAS "continue" form with a line something like:

`<input type=\"hidden\" name=\"password\" value=\"$hid\">`

or

`<input type=\"hidden\" name=\"password\" value=\"$tok\">`

**Comment by bluewavenet** [comment]
@garciave 
**Note**
With regard to your binauth script:
As I mentioned earlier, **_only with "auth_client"_**, does NDS supply the arguments:
$1=method (=auth_client in this case)
$2=clientmac
$3=username
$4=password
$5=redir
$6=useragent
$7=clientip

**Comment by garciave** [comment]
Yes, I know. I'm getting the token with the FAS.
Tks

**Comment by garciave** [comment]
@bluewavenet 

"Then generate a random number.... That is all the token is after all."

Excellent idea!!!

Tks a lot

**Comment by bluewavenet** [comment]
It is not appropriate to use certain aspects of ndsctl within Binauth as doing so causes a deadlock.
NDS/ndsctl can easily detect such attempts and block them. There is no such restriction within PreAuth or FAS scripts.
