### ISSUE TITLE
how do i tell NDS to enable connexion for certain client when using FAS

### ISSUE THREAD

**Issue by CharguiTaieb** [nodogsplash/nodogsplash#512]
Hi 
I want to know how do i tell NoDogSplash to enable connexion for specific client after login into my remote login page.

Beside that i want to know why sometime NoDogSplash  doesn't provide the IV when using (fas_secure_enabled = 2).

Thanks for your help.

**Comment by bluewavenet** [comment]
@CharguiTaieb 
We discussed much of this in issue #506 but I know the concept can be difficult to initially understand.

> how do i tell NoDogSplash to enable connexion for specific client after login 

This link to the documentation describes how to send the request for authentication to NDS:
https://nodogsplashdocs.readthedocs.io/en/stable/fas.html#post-fas-processing

The supplied fas-aes.php script is a fully functional example so you can see actual working code.
I did suggest you try using fas-aes.php so you can get experience with it before creating your own script and still think this will be worthwhile.  

> i want to know why sometime NoDogSplash doesn't provide the IV when using (fas_secure_enabled = 2).

The example you posted in #506 showed this. The problem is not that the IV is not supplied, but a problem that the entire query string is truncated to the maximum permitted length of 4KB.

This happens because your encrypted payload is too large. The system log will show the error.
As you add custom parameters, the length of the query string will grow. You must be sending a large amount of data, or have made a coding error in your fas script.
