### ISSUE TITLE
Offline issues

### ISSUE THREAD

**Issue by bomboem** [nodogsplash/nodogsplash#557]
Hi, while I'm making my own preauth script and trying a few things, I also attempted to run Nodogsplash in an "offline" mode, but I have some issues. As I read in other issue threads in this repo about making Nodogsplash work offline. As mentioned in all the threads, I added the line 
```address=/#/192.168.220.1/``` to ```/etc/dnsmasq.conf```. 

*BUT* when I connect my phone to this AP now, it does detect that there is a captive portal because the "Log in to this network" notification appears. When I click this notification, normally my device would open the CPD browser screen showing the output of my preauth script, but now, with that line added in ```dnsmasq.conf``` and no connection to the Internet, this shows up:
```
Not Found
The requested URL was not found on this server.

Apache/2.4.38 (Raspbian) Server at connectivitycheck.gstatic.com Port 80
```
and when I try this on my iPhone test device (iPhone 5S), this appears:
```
Not Found
The requested URL was not found on this server.

Apache/2.4.38 (Raspbian) Server at captive.apple.com Port 80
```
And even weirder, on my windows 10 Toshiba laptop, the default Apache2 for raspbian page opens up, not even the "Not found" message.

None of the devices show my preauth script output. Do you have any idea why?

**Comment by bluewavenet** [comment]
@bomboem 
You obviously have Apache server at 192.168.220.1:80, so are getting exactly what would be expected.

**_Offline mode needs its own section in the documentation, even though NDS does not support it directly - this is definitely on my todo list._** :-D

The proper setting for dnsmask is to return some random "Internet valid" ip address, rather than the gateway address or even a "private" ip address.
Note, remember this is an all or nothing configuration, once set you cannot access the Internet because DNS no longer resolves anything sensible.

From #328 

> Newer versions of client CPD seem to be checking for possible DNS rebind exploits.
> Returning to 192.168.1.1 for all enquiries looks just like, or in fact is, a rebind exploit, so devices with a CPD doing this check will not connect.
> The CPD is just looking for a positive return from its DNS enquiry, so any public address will do. eg:
> uci add_list dhcp.@dnsmasq[0].address '/#/121.122.123.124'
> uci commit dhcp

Obviously the uci commands apply to OpenWrt, but on other OS you would set 121.122.123.124 directly in the dnsmasq.conf file.

**Comment by bluewavenet** [comment]
@bomboem 
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560

**Comment by bluewavenet** [comment]
@lynxis 
This issue can be closed.
