### ISSUE TITLE
NDS 4.5 PROBABLY NOT STARTED ISSUE

### ISSUE THREAD

**Issue by diegotg97** [nodogsplash/nodogsplash#559]
Hi, I have a router GLINET MT300NV2 which has an OpenWrt version (19.07.2). 

I downloaded this ipk image of NDS from releases webpage: 

- nodogsplash_4.5.0-1_mipsel_24kc.ipk

Everything seems to go fine with the installation of NDS, It creates the folders and nodogsplashconfig file... the problem is that when i run command NDSCTL it throws me an error:

- ndsctl: nodogsplash probably not started (Error: No such file or directory)

Please, any help is appreciated... i need to upgrade my NDS version in my router... Thanks!

![Screenshot from 2020-04-11 03-01-42](https://user-images.githubusercontent.com/60304752/79038757-7f111b00-7ba1-11ea-9fd8-cfe4d029e5f8.png)

**Comment by bluewavenet** [comment]
@diegotg97 
It works well on the mt300n-v2. The most likely cause of your problem is the version of libmicrohttpd included in OpenWrt 19.07.x is outdated. This is an easy fix in the nds config however.
But first lets check if this is actually the problem.
Run:
```
service nodogsplash restart
logread | grep nodogsplash
```
If you see the error about libmicrohttpd (MHD) then all you have to do is to turn on the use_outdated_mhd option in the config file.

ie
`	option use_outdated_mhd '1'`

Save the config then restart nodogsplash again.

**Comment by diegotg97** [comment]
Thank you very much @bluewavenet it worked!

**Comment by bluewavenet** [comment]
@diegotg97 
See:
Version 5.0.0 - FAS API Moved to OpenNDS #560

**Comment by lynxis** [comment]
@diegotg97 is it working for you now?
