### ISSUE TITLE
Modifying firewall code to work on DNS as well as ip addresses

### ISSUE THREAD

**Issue by npateman** [nodogsplash/nodogsplash#59]
Hi there,

I have a real need to be able to allow certain domain names through the firewall before authentication, this is down to the resource itself being globally distributed so the ip changes with almost every request.  I'm sure I read in here that this has been requested before but was told it's tricky to do, would anyone have any pointers of where to start or maybe a reason it's not possible?

Nick.

**Comment by npateman** [comment]
This is hopefully no longer an issue of mine as I've thought of tackling it from the other side rather than trying to hash this into working.

**Comment by mwarning** [comment]
Hi, a domain might resolve to different IP addresses each time you try to resolve it. So it is not easy to allow a domain by itself. There are several not so trivial workarounds. (e.g. see the https://github.com/nodogsplash/nodogsplash/wiki/FAQ). You might alo have a better audience using the mailing liste. :-)

**Comment by npateman** [comment]
Thanks mwarning, so I didn't reply sooner, the weekend was a bit hectic and I forgot I has this notification!  thanks, i'll look at the FAQ and try the mailing list although I've almost given up on fudging iptables into submission.

**Comment by ArtMartin89** [comment]
hello, I also need to open some domains by name because of often ip changing.
In openWRT wiki there's an example how to Restrict access https://wiki.openwrt.org/doc/howto/wireless.hotspot.nodogsplash#restrict_access_to_domains

But I'm totally not god with coding, and as far as I understand if we change this line

`iptables -t nat -I ndsOUT -p tcp -s 10.20.30.0/24 -d $ip --dport 80 -j DNAT --to 10.20.30.1:80`

to the rule which will open the access to $ip it'll work

So the question is how to change it for not restricting but for allowing access?
