### ISSUE TITLE
Which one do I choose FAS, binauth or preauth?

### ISSUE THREAD

**Issue by prasadph** [nodogsplash/nodogsplash#603]
I am trying to set up a Captive login with a dynamically changing list of users. I have managed to setup binauth for a single user login setup using the docs. Do I need to consider BInauth or preauth as options. I am not able understand the difference the from binauth.

**Comment by bluewavenet** [comment]
@prasadph 
FAS (forward authentication service) , PreAuth (a special case of FAS) and BinAuth (a post authentication processor) are no longer supported by Nodogsplash. 
This functionality has been moved to openNDS, and NoDogsplash has been stripped to a minimum to allow use as a basic captive portal on legacy devices with very restricted resources.

See:
https://github.com/openNDS/openNDS
https://opennds.readthedocs.io

I would suggest you migrate to openNDS. The current version is 8.1.1 and is available as an installable package on OpenWrt or as a compilable package for use on generic Linux.
For guidance please open an issue at openNDS.

Please state what hardware and operating system are you using along with a brief outline of the requirement.

**Comment by prasadph** [comment]
@bluewavenet thanks for the reply. I am using Raspberry PI 4  model B. 
Is it still better to move to opennds?
My requirement is to create captive portal for a workplace wifi with option for remotely adding new users.  
I started from this article [https://pimylifeup.com/raspberry-pi-captive-portal/](https://pimylifeup.com/raspberry-pi-captive-portal/)

**Comment by bluewavenet** [comment]
@prasadph 

>  My requirement is to create captive portal for a workplace wifi with option for remotely adding new users.

openNDS has an API to enable many options for doing just this. In fact the default mode enables a built in set of dynamically generated html pages for user login. It is driven by a PreAuth login script that is specifically written to make it easy to customise the credentials the user has to enter.
Given that the bulk of work is already done in openNDS with various example scripts provided, I would say most definitely it is better to move to it.

Do bare in mind though, that the choice of a Rpi, even a model  4B, is not a good choice as it is designed to be a "personal computer" or IoT device, and **does NOT make a good router** due to the chipset used for its wireless and the fact it only has a single ethernet port.

A modern Wireless router running OpenWrt would provide much better performance at a significantly lower cost (I am talking of **total** hardware cost in the region of ~$25 USD for this type of application).

**Comment by prasadph** [comment]
Thanks for advice @bluewavenet. Closing issue.
