### ISSUE TITLE
nodogsplash serves linked .css files into splash.html with mime-type text/html (not text/css) 

### ISSUE THREAD

**Issue by vadim1r** [nodogsplash/nodogsplash#63]
Linking external style sheets in header of splash.html:

```
<link href="$imagesdir/style.css" type="text/css" rel="stylesheet"></link>
```

or

```
<style>
    @import url("$imagesdir/style.css");
</style>
```

returns content of stylesheet with mime-type text/html (not text/css, as expected).

So browsers doesn't load stylesheets properly.

**Comment by mwarning** [comment]
Will probably be fixed along with #46

**Comment by Onuonga** [comment]
Was this ever fixed as I can see my css gets the response code 200 but it delvers as txt/html and this results in it not being loaded. Interestingly, when you look at the page source and you click on the html it resolves it like a web page and loads another redirect web page. Any clue how to go by this?

**Comment by bluewavenet** [comment]
@Onuonga 
Ask yourself why you need separate css files for a simple splash page.
If you still do, read my workaround of 21st May in #46 

"The web server built into Nodogsplash is very simple and basic. Fine for a simple splash page.
Your problem here is not anything to do with issue #46
Why do you need separate css files for a simple page? If you are trying to do something much more sophisticated you would be better of using the uhttpd already running on OpenWrt. This is by default not accessible to clients when at the preauth stage. You need to allow access by adding an entry into nodogsplash.conf

With your css files under /www/mycss/bootstrap.min.css, add the following line to nodogsplash.conf:
# FirewallRuleSet: preauthenticated-users
FirewallRule allow tcp port 80 to [ipaddress_openwrt]

You do not need libevhtp libneon or libmicrohttpd .

Link to the css files at:
http://openwrt.lan/mycss/[cssfile].css "
