### ISSUE TITLE
DNS tunneling protection for pre-authenticated users

### ISSUE THREAD

**Issue by maxguru** [nodogsplash/nodogsplash#73]
I see a lot of captive portals, including nodogsplash, have a problem where users can use some tool like iodine to bypass the captive portal.

You have to allow port 53 through in order to have the users be able to resolve names.  However, this allows users to set up their own DNS server with custom code and tunnel through that without any issues.

I propose the following solution,

Integrate a fake DNS server into nodogsplash that would reply with some random IP addresses and very low TTL (1 second?) for A and AAAA records, some random values for CNAME records and maybe no reply for other kinds of records (or whatever the desired behavior is).  Also, some iptables rules need to be added as well to redirect all traffic to port 53 (any host) to the port that our fake DNS server would be running at.  This is similar (in a way) to what the captive portal is already doing with HTTP.  This way, it would be impossible to establish any kind of link for pre-authenticated users with the outside world over DNS.

Any thoughts on this?

**Comment by bluewavenet** [comment]
Issue #80 might be relevant - Firewall Ruleset User to Router...

**Comment by 4L3Xx** [comment]
Actually not really.  If I understand this right, port 80 is allowed to the router because it is basically running a transparent proxy for the pre-authenticated users.  This works great, because users think they are accessing google.com or whatever, but actually get served our own web page.  The DNS for pre-authenticated users does not have any kind of thing like this.

The DNS forwarding (or actual recursive DNS server) is running on the router for all users, including pre-authenticated.  Pre-auth users DO need some kind of DNS to work because otherwise they will not be able to reach any site, including the splash page.  So what does nodogsplash do? It goes, whatever, let them access router DNS daemon (which will actually resolve real records and allow iodine to work).

What we need is actual fake DNS daemon running on another port (not 53) and iptables rules for pre-authenticated users to do transparent proxy thing for requests on port 53 (just like with port 80).  Then, this fake DNS server will serve fake records (set up in such a way to be fail-proof) with 1 second TTL.  We might also want to have the authentication action to hang around for 1 second before confirming authentication (to allow their OS DNS cache to expire).

**Comment by bluewavenet** [comment]
Actually firewall ruleset user to router seems to be broken, at least for allow port 80. NDS  redirects to port 2050 by default where the splash page is served up by the nds web server.
If port 80 was accessible then the OpenWrt httpd would be available. It is not until authenticated unless you specify the gateway ip address and port 80 in ruleset preauth. I think dns access to the router only must be hard wired and not controlled by user to router and this is a bug that has gone unnoticed up to now. If the user machine has locally configured dns (rather than dhcp configured) it should get nowhere. 
For NDS to work when a user machine is configured manually with dns server address's, the idea was to allow preauth access straight through and IF this is enabled in the firewall, yes iodine is a problem.
Iodine depends upon a clear route out through the gateway to an iodined server. The dns on a router is just a forwarder to the isp's dns servers or servers pointed to by the router and no amount of tunnelling will get you through. At least that is how I interpret what is happening here :)

**Comment by 4L3Xx** [comment]
Yes, something like that.  So, what we need is all incoming packets to any host port 53 redirected to our fake DNS server (port 2049?) for pre-authenticated users.  This fake server would serve some sane records that would expire in 1 second.  This way, even if users configure their own DNS servers, everything still keeps working as it should.

There are some libraries available that can be used to add such a fake DNS server to nds.  I am currently considering taking on this project.  I wonder if it would be accepted into the code base.

**Comment by bluewavenet** [comment]
To stop people with manually configured dns from tunnelling out all you need to do is comment out the preauth port 53 entries in nodogsplash.conf ie:
FirewallRuleSet preauthenticated-users {
 # For preauthenticated users to resolve IP addresses in their initial
 # request not using the router itself as a DNS server,
 # you probably want to allow port 53 udp and tcp for DNS.
 #  FirewallRule allow tcp port 53	
 #  FirewallRule allow udp port 53
 #  FirewallRule allow tcp port 443
 # For splash page content not hosted on the router, you
 # will want to allow port 80 tcp to the remote host here.
 # Doing so circumvents the usual capture and redirect of
 # any port 80 request to this remote host.
 # Note that the remote host's numerical IP address must be known
 # and used here.  
 #    FirewallRule allow tcp port 80 to 123.321.123.321
FirewallRule allow tcp port 80 to 10.168.1.1
}

This will leave them with just a browser error and no splash page. But then how many users even know what dns is let alone manually configuring it. A simple stub rule that redirects port 53 to any outside address to port 53 on the router would allow the small number of people with manually configured dns to get the splash page.
A bigger issue that could be resolved at the same time is https access by preauth. It is a growing number of users with an https site set as home page that will not get splash unless they know or are told to try a plain html site first. (see my 433 entry commented out above - this allows them out, they get a splash as soon as they hit port 80 - bit of a cop out work around, but then 99.999% of them are pretty dumb/innocent. If it is a Free Wifi hotspot and all you are concerned about is TOS acceptance then it is not a show stopper )

**Comment by 4L3Xx** [comment]
The issue is, it doesn't matter if they have self-configured dns or if they are using dhcp served dns servers.  What matters is they can punch through dns to the outside world using something like iodine.  This needs to be fixed imho.

You could capture https requests as well with https server using self-signed cert.  Browsers will complain but most users may be able to still get to the splash page by accepting the bad cert.

**Comment by bluewavenet** [comment]
If the dhcp configured dns server address is the dns forwarder on the nodog router then port 53 can be blocked for passthrough. This will stop iodine from tunnelling. It can only tunnel when packets are passed through the firewall. 
They cannot just "punch through" if the firewall is blocking them.
The entry in  Firewall Ruleset User to Router allows access to the router's own dns and the one in Preauth blocks passthrough . The following is the .conf setup I use. 

Iodine is blocked.

But you do not get a splash page if you are configured manually for dns (and the hotspot appears broken to such users). :

FirewallRuleSet preauthenticated-users {
      FirewallRule allow tcp port 80 to 10.168.1.1 #change to your GatewayInterface address
}
# end FirewallRuleSet preauthenticated-users

FirewallRuleSet users-to-router {
   FirewallRule allow udp port 53	
   FirewallRule allow tcp port 53	
# If you comment out the port 67 entry that follows (dhcp) you will effectively brick your router.
   FirewallRule allow udp port 67
   FirewallRule allow tcp port 22
   FirewallRule allow tcp port 80
   FirewallRule allow tcp port 443
}
# end FirewallRuleSet users-to-router

**Comment by 4L3Xx** [comment]
If you block port 53 for preauth users then they will not be able to get to the splash page due to DNS resolution error for whatever domain they are trying to access.  If you don't block port 53 then they can use iodine.  Whatever is running on port 53 on the router doesn't differentiate between preauth users and auth'ed users.  This is unsolvable without adding fake DNS server.

BTW, blocking port 67 doesn't brick your router, you can still get to it if you configure networking statically as far as I know.

**Comment by bluewavenet** [comment]
I see the problem. Sorry about the odd formatting in my prev post.
My firewall rulesets are:
FirewallRuleSet preauthenticated users (only one entry ie everything else blocked):
FirewallRule allow tcp port 80 to 10.168.1.1 [change to your GatewayInterface address]

and for FirewallRuleset users-to-router:
FirewallRule allow udp port 53	
FirewallRule allow tcp port 53	
FirewallRule allow udp port 67
FirewallRule allow tcp port 22
FirewallRule allow tcp port 80
FirewallRule allow tcp port 443

This allows ONLY access to local services. dnsmask provided dns on port 53.
Iodine is prevented from using direct connection to the iodined server on the outside so has to try to use dnsmask. In theory this might still work but in practice it does not at least on the setup I have been using. (barrier breaker on alix2d2, Ubiquity air gateway/ air router and bullet). By default in NDS and in most hotspot cp's in the wild port 53 is left open and iodine can get right through. Perhaps it does work but is incredibly slow - I did not investigate. For my purposes I am only looking for TOC acceptance followed by an advertising splash page so there is no real advantage in iodine, just click accept and get 6 hours worth of full speed before you have to click again.
Next project might be different though - so I am interested.
Re bricking: With my firewall rulesets above, if you then comment out port 67 you do not get to preauth. Then even if you static configure, NDS will block ALL ports but 80 and on there throw an error re no valid token . The only way I could get in was ssh on ipv6. Glad I left it running ;)

**Comment by netomx** [comment]
FirewallRule allow udp port 53 to <you-dns-server>

**Comment by bluewavenet** [comment]
@netomx : to what and why? ;)

**Comment by netomx** [comment]
Hahaha, the comment was modified. It is to protect from dns tunneling. With it, you can use iodine and it will connect succesfully. With

FirewallRule allow udp port 53 to yourdnsserverip

Will just work withour raw mode. Disable edns from dnsmasq and it will be succesfully blocked.

**Comment by lynxis** [comment]
a side note ;) we should put this into a faq list

**Comment by nihilus** [comment]
Actually you should do DNAT on port 53 for pre-authenticated users to another instance of the DNS-server which gives back a catch-all response.

**Comment by maxguru** [comment]
It would be nice if nodogsplash actually provided this 'fake' DNS server (just like the built in http server) and set up the DNAT automatically for pre-authenticated users.  There is zero reason for not having it.  Nobody wants to allow DNS tunneling on their network.  Also, it takes some doing to set this up.  Why not just add this feature to nodogsplash and save everyone the trouble?

**Comment by CGretski** [comment]
I prevent DNS tunneling by using dnsmasq to respond with spoofed DNS replies-
in dnsmasq.conf add `address=/#/192.168.1.1`
which will cause all queries to return 192.168.1.1  (use the IP address of your captive portal)

Then use iptables to force all DNS queries to dnsmasq (except those already destined for it):

`iptables -t nat -I ndsOUT 1 ! -d 192.168.1.1/32 -p tcp -m tcp --dport 53 -j REDIRECT
iptables -t nat -I ndsOUT 1 ! -d 192.168.1.1/32 -p udp -m udp --dport 53 -j REDIRECT
`
I haven't found a way to have NoDogSplash create those iptables rules automatically

**Comment by maxguru** [comment]
@CGretski, Wouldn't that prevent you from using dnsmasq for regular use, for example, to act as a DNS forwarder for authenticated users?

**Comment by CGretski** [comment]
Good point;
Perhaps then at the end of the ndsOUT chain; so it will be overridden by the accept/all marked (authenticated) traffic.
so `-A ndsOUT`  rather than `-I ndsOUT 1`
Or you could force them through a proxy which handles its own DNS.

**Comment by netomx** [comment]
Why not FirewallRule allow udp port 53 to 192.168.1.1?

**Comment by CGretski** [comment]
As in my example 192.168.1.1 is the captive portal hosting the spoofing DNS server.
There is already access to it for all users; but it does not return real DNS results; hence needing access to a real DNS server once authenticated.
